Fixes for timeline semaphore
KhronosGroup/Vulkan-Samples pull request #1065
Opened 2024-06-10 15:00 UTC by bryce-young-mobica

## Description
Reworked the timeline semaphore sample to prevent it crashing on Windows. 

The only obvious trigger for the crash that I could observe was the main thread calling "vkDeviceWaitIdle" whilst the compute thread was in "wait_timeline_gpu". To avoid this, I removed the "wait/signal_timeline_gpu" calls (opting to attach the "VkTimelineSemaphoreSubmitInfo" to the queue submissions instead), and restructured the compute/graphics work stages to prevent the compute thread running ahead and submitting (potentially blocking) work.

- Replaced the "wait/signal_timeline_gpu" calls with "VkTimelineSemaphoreSubmitInfo" added to the queue submissions
- Added an enum for identifying the timeline stages, to make it easier to read and debug the signals/waits
- Moved the rendering work to a seperate thread, leaving the main thread responsible for acquiring and presenting the swapchain image, and signalling the timeline semaphore.

Fixes #588

Tested on Windows
Tested with shared queue for compute and graphics
## General Checklist:

Please ensure the following points are checked:

- [X] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [X] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [X] I have commented any added functions (in line with Doxygen)
- [X] I have commented any code that could be hard to understand
- [X] My changes do not add any new compiler warnings
- [] My changes do not add any new validation layer errors or warnings
- [X] I have used existing framework/helper functions where possible
- [X] My changes do not add any regressions
- [X] I have tested every sample to ensure everything runs correctly
- [X] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [X] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [X] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

 If this PR contains framework changes:
 - [X] I did a full batch run using the `batch` command line argument to make sure all samples still work properly

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [X] I have tested the sample on at least one compliant Vulkan implementation
- [X] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)
- [X] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [X] Any dependent assets have been merged and published in downstream modules
- [X] For new samples, I have added a paragraph with a summary to the appropriate chapter in the readme of the folder that the sample belongs to [e.g. api samples readme](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/api/README.adoc)
- [X] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/conditional_rendering)
- [X] For new samples, I have added a link to the [Antora navigation](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

2024-06-10 15:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-Samples?pullRequest=1065) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-Samples?pullRequest=1065) before we can accept your contribution.<br/><hr/>**Bryce Young** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-Samples?pullRequest=1065) it.</sub>

2024-06-12 10:42 UTC, SaschaWillems requested changes

2024-06-12 10:42 UTC, SaschaWillems commented on samples/extensions/timeline_semaphore/CMakeLists.txt
Looks like all line endings were changed with this PR, making it look like this whole file changed. That makes it hard to review. Can you revert the line ending changes?

2024-06-12 10:42 UTC, SaschaWillems commented on samples/extensions/timeline_semaphore/README.adoc
Looks like all line endings were changed with this PR, making it look like this whole file changed. That makes it hard to review. Can you revert the line ending changes?

2024-06-12 12:14 UTC, bryce-young-mobica commented on samples/extensions/timeline_semaphore/CMakeLists.txt
Sorry, meant to create the PR for a forked repo (haven't used github much). Thanks for the review though, I'll resubmit this PR once from our fork when it's ready

2024-06-12 12:14 UTC, closed without merging

2024-07-20 13:24 UTC, SaschaWillems commented
Any update on this? Would be great to have that sample properly work on Windows.

2024-08-06 10:37 UTC, bryce-young-mobica commented
Sorry for the delay. 
I made the changes you suggested, and opened a new PR here: https://github.com/KhronosGroup/Vulkan-Samples/pull/1125 (didn't see the reopen option until after I'd created it).