Index buffer size is using vertex_buffer_size
KhronosGroup/Vulkan-Samples pull request #31
Opened 2020-01-07 03:17 UTC by jherico

## Description

Apparent simple copy paste error.  When creating the index buffer for the GUI, it uses `vertex_buffer_size` instead of `index_buffer_size`

## Checklist:

Ugh, seriously, guys, come on.

2020-01-09 11:05 UTC, wasimabbas-arm commented
LGTM, please revert the copyright headers commit.

2020-01-09 11:34 UTC, ZandroFargnoli requested changes
@jherico Thank you for the fixes, I see you have a few PRs changing many of the files. You should only need to change the copyright for files you've added/modified.

If you can revert your commits and just add -2020 to the `.cpp` file we can then merge it.

2020-01-09 14:39 UTC, jherico commented
@ZandroFargnoli  @wasimabbas-arm copyright headers reverted.  However, the gui file I changed contains two copyright lines, one for "arm and contributors" which I updated, and one specifically for Sascha, which I didn't touch.  I don't know if the CI check is smart enough to differentiate between them.

2020-01-13 17:31 UTC, wasimabbas-arm commented
> @ZandroFargnoli @wasimabbas-arm copyright headers reverted. However, the gui file I changed contains two copyright lines, one for "arm and contributors" which I updated, and one specifically for Sascha, which I didn't touch. I don't know if the CI check is smart enough to differentiate between them.

This is a good question. We should probably change the copyright script to look for all copyrights. I have created https://github.com/KhronosGroup/Vulkan-Samples/issues/42

2020-01-13 17:49 UTC, merged