Texture compression comparison
KhronosGroup/Vulkan-Samples pull request #359
Opened 2021-09-27 02:55 UTC by gpx1000

## Description

This sample demonstrates how to use different types of compressed GPU textures in a Vulkan application, and shows 
the timing benefits of each.

## Tested Environments

Windows 10 / Ubuntu Linux
GeForce 3060 / GeForce 2080 / GeForce 1070
Vulkan version: 1.2.189
Sample Assets changes
depends upon compressed textures found in KhronosGroup/Vulkan-Samples-Assets#15

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

2021-10-04 18:51 UTC, SaschaWillems commented
Works fine for me on my desktop GPU.

Two remarks though:
- Switching between target formats, I can't see any difference in the rendering output. Judging by the code, it looks like it's only benchmarking transcoding to a different format. In my opinion it would make sense to use the transcoded textures for the displayed scene. Not sure if that's easily possible with the framework.
- I'd like to see some documentation. There are now comments in the code and the sample doesn't include a readme. Having a few lines of text about what the sample does would be appreciated :)

2021-10-06 10:53 UTC, gary-sweet requested changes
This isn't working for me. It tries to use formats that are unsupported.

available_texture_formats is calculated by get_available_texture_formats(), but doesn't appear to actually be used anywhere.

2021-10-12 17:32 UTC, gpx1000 commented
@gary-sweet please give the latest another shot to see if it's working for you now.

2021-10-13 08:28 UTC, gary-sweet commented
> @gary-sweet please give the latest another shot to see if it's working for you now.

@gpx1000 Yep, that's much better thanks.

Can I suggest adding "vkb::StatIndex::gpu_ext_read_bytes" to the requested stats for this sample?
It very obviously then shows a reduction in read bandwidth when choosing a compressed texture, which helps to explain the small performance improvement.

2021-10-13 22:44 UTC, gpx1000 commented
I added vkb::StatIndex::gpu_ext_read_bytes to the stats requested.  I don't have a device that supports them however, so @gary-sweet will need to request validation that this is all that was required and that it works for what you want displayed here.

2021-10-18 10:50 UTC, gary-sweet submitted a review, later dismissed
LGTM, thanks.

2021-10-25 17:51 UTC, SaschaWillems submitted a review, later dismissed
LGTM. All my points have been addressed 👍

2021-10-26 14:52 UTC, TomAtkinsonArm reviewed
LGTM

2021-10-26 14:52 UTC, TomAtkinsonArm commented on samples/CMakeLists.txt
> +    "texture_cmpression_comparison"
`texture_compression_comparison`

2021-10-26 16:09 UTC, gpx1000 commented on samples/CMakeLists.txt
> +    "texture_cmpression_comparison"
thanks!

2021-10-26 16:51 UTC, SaschaWillems approved these changes

2021-10-27 08:09 UTC, TomAtkinsonArm approved these changes

2021-10-27 08:29 UTC, gary-sweet approved these changes

2021-11-02 15:00 UTC, merged

2021-11-02 15:00 UTC, marty-johnson59 commented
Merging with 3 approvals  LMK if issues..