Change vkb::HPPVulkanSample from a facade over vkb::VulkanSample to a self-contained class using vulkan.hpp
KhronosGroup/Vulkan-Samples pull request #410
Opened 2021-12-07 13:03 UTC by asuessenbach

## Description

Replacing this part of the framework shows how to manage some more resources using vulkan.hpp.

In order to do so, a couple of new facade classes and functions are introduced in `common/hpp_strings.h`, `common/hpp_utils.h`, `core/hpp_command_buffer.h`, `core/hpp_image_view.h`, `hpp_gui.h`, `platform/hpp_application.h`, `platform/hpp_window.h`, `rendering/hpp_render_frame.h`, `rendering/hpp_render_pipeline.h`, `rendering/hpp_render_target.h`, and `stats/hpp_stats.h`

The vulkan.hpp-based classes and facades in `common/hpp_vk_common.h`, `core/hpp_device.h`, `core/hpp_instance.h`, `core/hpp_physical_device.h`, `core/hpp_swapchain.h`, `hpp_api_vulkan_sample.[cpp|h]`, `hpp_gltf_loader.h`, `platform/hpp_platform.h`, `rendering/hpp_render_context.h`, `api/hpp_dynamic_uniform_buffers/hpp_dynamic_uniform_buffers.[cpp|h]`, `api/hpp_hello_triangle/hpp_hello_triangle.[cpp|h]`, and `api/hpp_texture_loading/hpp_texture_loading.[cpp|h]` needed some adjustments and additions.

In addition to that, some consts needed to be spread over the framework in `core/command_buffer.[cpp|h]` and `platform/platform.[cpp|h]`.

And, finally, the dependency of vkb::Window and its derivatives on vulkan.hpp is removed.

I have tested it on Window10 on nvidia HW.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

2021-12-07 14:14 UTC, asuessenbach commented
Any idea anyone what's wrong with the failing Android build?

2021-12-19 19:32 UTC, SaschaWillems commented
Thanks for the contribution :). Looks good to me so far, though I'd like to take a deeper look at this before approving.

2022-01-17 10:59 UTC, gary-sweet requested changes
The direct-2-display changes don't work for me. I get a segv when running hpp_hello_triangle.

It looks like the vkGetPhysicalDeviceDisplayPropertiesKHR function pointer is null.

2022-01-18 10:01 UTC, asuessenbach commented
@gary-sweet I see... I need to add some direct-2-display specific code (initialize volk) to hpp_hello_triangle, then.
Is `VK_USE_PLATFORM_DISPLAY_KHR` the correct define to check for that platform?

2022-01-18 12:08 UTC, gary-sweet commented
Yes, VK_USE_PLATFORM_DISPLAY_KHR is the one.

2022-01-18 15:11 UTC, gary-sweet approved these changes, later dismissed
Thanks. That fixes the issue for me.

2022-01-24 15:18 UTC, asuessenbach commented
Is there anything I can do to get someone to review this?

2022-01-24 16:47 UTC, SaschaWillems commented
I'll try to review it this weekend :)

2022-01-25 01:02 UTC, gpx1000 reviewed
I limited my review to changes only.  Some day we need to whole sale fix all of the warnings.  These changes work on a linux device here and look good to me!  Thanks for the work!

2022-01-25 01:02 UTC, gpx1000 commented on framework/common/hpp_strings.h
> +	return vkb::to_string(static_cast<VkExtent2D const &>(extent));
I'm confused about the need for this?  can't we use vkb::to_string as needed?  or even using namespace?

2022-01-25 01:02 UTC, gpx1000 commented on framework/common/hpp_utils.h
> +	vkb::screenshot(reinterpret_cast<vkb::RenderContext &>(render_context), filename);
same as with the to_string and the generate_all below.  What are we gaining from this?

2022-01-25 01:02 UTC, gpx1000 commented on framework/common/hpp_strings.h
> +const std::string to_string(vk::Extent2D const &extent)
const not needed in the return type.  It is const qualified at the top level which means it wouldn't effect const correctness and could reduce readability.

2022-01-25 01:02 UTC, gpx1000 commented on framework/common/hpp_vk_common.h
> + * @brief facade helper functions and structs around the functions and structs in common/vk_commmon, providing a vulkan.hpp-based interface
vk_commmon has one too many 'm' characters.

2022-01-25 01:02 UTC, gpx1000 commented on framework/common/hpp_vk_common.h
> +	uint32_t new_queue_family{VK_QUEUE_FAMILY_IGNORED};
old_queue_family /new_queue_family don't appear to be used yet although given that they are used in hte ImageMemoryBarrier struct it makes sense to leave them?

2022-01-25 01:02 UTC, gpx1000 commented on framework/common/hpp_vk_common.h
> +inline bool is_depth_stencil_format(vk::Format format)
function isn't used yet; it makes sense to keep it as it's used in the vk_common.h file which this emulates I think?

2022-01-25 01:02 UTC, gpx1000 commented on framework/core/hpp_command_buffer.h
> +	vk::CommandBuffer get_handle() const
this hides a non-virtual get_handle() from VulkanResource::get_handle.

2022-01-25 01:02 UTC, gpx1000 commented on framework/core/hpp_debug.h
> +	virtual void set_debug_name(VkDevice     device,
virtual is redundant when the function is already marked with override.  (same through out this file).

2022-01-25 01:02 UTC, gpx1000 commented on framework/core/hpp_debug.h
> +	    cmd_begin_label(VkCommandBuffer command_buffer, const char *name, glm::vec4 color = {}) const override
default parameters aren't great practice on overridden functions because the value of the default will depend upon the static type of the object while the virtual function call will depend upon the dynamic type of the object. (clang tidy will complain correctly on this).  Same else where in this file.

2022-01-25 01:02 UTC, gpx1000 commented on framework/core/hpp_device.h
> +	                requested_extensions)
requested_extensions is passed by value and only copied once, use std::move() on it to avoid unnecessary copies

2022-01-25 01:02 UTC, gpx1000 commented on framework/core/hpp_swapchain.h
> +	const vk::Extent2D &get_extent() const
get_extent hides a non-virtual function from Swapchain class

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_api_vulkan_sample.h
> +	virtual void create_render_context(vkb::platform::HPPPlatform const &platform) override;
virtual or override not both, and prefer override.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_gui.h
> +			pssci.push_back(*reinterpret_cast<VkPipelineShaderStageCreateInfo const *>(&ci));
push_back called inside a loop.  It's probably better to pre-allocate what you need, then assign values in the loop.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_gui.h
> +	vkb::HPPDrawer &get_drawer()
this hides a non-virtual from GUI

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_gui.h
> +	bool update_buffers()
this hides a non-virtual from GUI

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.cpp
> +		const auto &key_event = static_cast<const KeyInputEvent &>(input_event);
avoid using static_cast to downcast from a base class.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.cpp
> +			if (!vkb::common::graphs::generate_all(get_render_context(), *scene.get()))
redundant get called on smart pointer (just remove the get and it'll work).

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.cpp
> +void HPPVulkanSample::set_viewport_and_scissor(vkb::core::HPPCommandBuffer const &command_buffer, const vk::Extent2D &extent) const
function can be made static.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.cpp
> +	// To be overriden by sample
two 'd's' in overridden.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	virtual ~HPPVulkanSample();
let's prefer override or final to virtual on child classes.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	virtual bool prepare(vkb::platform::HPPPlatform &platform) override;
virtual or override not both.  Prefer override (everywhere in this file).

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	virtual bool resize(const uint32_t width, const uint32_t height) override;
width and height are both const qualified, this only has effect in the function definitions so not needed here.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	void set_high_priority_graphics_queue_enable(bool enable)
set_high_priority_graphics_queue_enable isn't used but is used in the replaced class.  assumption is this is to be addressed.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	 * @brief Triggers the render pipeline, it can be overriden by samples to specialize their rendering logic
add a 'd' to overridden.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	 * @return Map of instance extensions and wether or not they are optional. Default is empty map.
whether needs an 'h'.

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	 * @param optional (Optional) Wether the extension is optional
whether needs an 'h.'

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	 * @param optional (Optional) Wether the extension is optional
whether needs an 'h'

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	 *        Should be overriden by the samples since they
overridden needs a d

2022-01-25 01:02 UTC, gpx1000 commented on framework/hpp_vulkan_sample.h
> +	/** @brief Set of device extensions to be enabled for this example and wether they are optional (must be set in the derived constructor) */
whether needs a h

2022-01-25 01:02 UTC, gpx1000 commented on framework/platform/glfw_window.h
> +	virtual VkSurfaceKHR create_surface(VkInstance instance, VkPhysicalDevice physical_device) override;
virtual or override but not both and prefer override

2022-01-25 01:02 UTC, gpx1000 commented on framework/platform/headless_window.h
> +	virtual VkSurfaceKHR create_surface(VkInstance instance, VkPhysicalDevice physical_device) override;
virtual or override but not both, prefer override.

2022-01-25 01:02 UTC, gpx1000 commented on framework/platform/hpp_application.h
> +	virtual bool prepare(vkb::Platform &platform) final
virtual or final, prefer final

2022-01-25 01:02 UTC, gpx1000 commented on framework/platform/hpp_platform.h
> +	vkb::platform::HPPWindow &get_window()
get_window hides a non-virtual function in Platform.

2022-01-25 01:02 UTC, gpx1000 commented on framework/rendering/hpp_render_context.h
> +	vkb::core::HPPCommandBuffer &begin(vkb::CommandBuffer::ResetMode reset_mode = vkb::CommandBuffer::ResetMode::ResetPool)
begin hides a non-virtual function.

2022-01-25 01:02 UTC, gpx1000 commented on framework/rendering/hpp_render_context.h
> +	vkb::rendering::HPPRenderFrame &get_active_frame()
get_active_frame hides a non-virtual function.

2022-01-25 01:02 UTC, gpx1000 commented on framework/rendering/hpp_render_frame.h
> +	vkb::rendering::HPPRenderTarget &get_render_target()
get_render_target hides a non-virtual function

2022-01-25 01:02 UTC, gpx1000 commented on framework/rendering/hpp_render_target.h
> +	const vk::Extent2D &get_extent() const
get_extent hides a non-virtual function

2022-01-25 01:02 UTC, gpx1000 commented on framework/rendering/hpp_render_target.h
> +	std::vector<vkb::core::HPPImageView> const &get_views() const
get_views hides a non-virtual function

2022-01-25 01:02 UTC, gpx1000 commented on framework/stats/hpp_stats.h
> +	HPPStats(vkb::rendering::HPPRenderContext &render_context, size_t buffer_size = 16) :
constructors that are callable with a single parameter need to be marked explicit.

2022-01-25 01:02 UTC, gpx1000 commented on samples/api/hpp_hello_triangle/hpp_hello_triangle.cpp
> +#include <hpp_hello_triangle.h>
personal preference however, unless it breaks something which it shouldn't; this should be reversed (hpp_hello_traingle.h) is found at the same folder as the cpp file.

2022-01-25 01:02 UTC, gpx1000 commented on samples/api/hpp_hello_triangle/hpp_hello_triangle.cpp
> +void HPPHelloTriangle::select_physical_device_and_surface(Context &context, vkb::platform::HPPPlatform &platform)
while we're at it (although I'm trying to limit my comments to only new changes these are easy to fix).  Could we rename the context parameter so it doesn't shadow the member variable context?  Also this function is safe to be made static.

2022-01-25 07:27 UTC, asuessenbach commented on framework/common/hpp_strings.h
> +	return vkb::to_string(static_cast<VkExtent2D const &>(extent));
This function (as well as all the other hpp-facade classes and functions) is just there to make the really vulkan.hpp-based classes look like they're in a completely vulkan.hpp-based environment: call that function without the need to explicitly cast the arguments to some non-vk-namespace stuff.

2022-01-25 07:37 UTC, asuessenbach commented on framework/common/hpp_utils.h
> +	vkb::screenshot(reinterpret_cast<vkb::RenderContext &>(render_context), filename);
Same answer as above. I just realized that the facade-comment was missing in these two files.

2022-01-25 07:41 UTC, asuessenbach commented on framework/common/hpp_strings.h
> +const std::string to_string(vk::Extent2D const &extent)
I just replicated the exact same interface (besides the vk-types) as the wrapped function, to make sure this function can be used in the exact same manner.

2022-01-25 07:44 UTC, asuessenbach commented on framework/common/hpp_vk_common.h
> +	uint32_t new_queue_family{VK_QUEUE_FAMILY_IGNORED};
I think, it makes sense to keep them.
The facade-classes/structs should be "as similar" as possible to the original classes/structs.

2022-01-25 07:47 UTC, asuessenbach commented on framework/rendering/hpp_render_target.h
> +	const vk::Extent2D &get_extent() const
That was my intention.
The facade-classes are supposed to return vk-namespace stuff.

2022-01-25 07:47 UTC, asuessenbach commented on framework/rendering/hpp_render_target.h
> +	std::vector<vkb::core::HPPImageView> const &get_views() const
Same answer as above.

2022-01-25 07:51 UTC, asuessenbach commented on framework/stats/hpp_stats.h
> +	HPPStats(vkb::rendering::HPPRenderContext &render_context, size_t buffer_size = 16) :
This is again (besides the vulkan.hpp-based types) the exact same interface as the wrapped constructor.
Should I adjust those two to be explicit?

2022-01-25 07:59 UTC, asuessenbach commented on samples/api/hpp_hello_triangle/hpp_hello_triangle.cpp
> +void HPPHelloTriangle::select_physical_device_and_surface(Context &context, vkb::platform::HPPPlatform &platform)
Good point!
I'll remove that parameter, as it's already available by the member variable.

2022-01-25 08:02 UTC, asuessenbach commented on samples/api/hpp_hello_triangle/hpp_hello_triangle.cpp
> +#include <hpp_hello_triangle.h>
Ok, will revert that.

2022-01-25 08:11 UTC, asuessenbach commented on framework/common/hpp_vk_common.h
> + * @brief facade helper functions and structs around the functions and structs in common/vk_commmon, providing a vulkan.hpp-based interface
Good catch.

2022-01-25 08:12 UTC, asuessenbach commented on framework/common/hpp_vk_common.h
> +inline bool is_depth_stencil_format(vk::Format format)
Agreed.

2022-01-25 08:13 UTC, asuessenbach commented on framework/core/hpp_command_buffer.h
> +	vk::CommandBuffer get_handle() const
Again, by intention. This function should return vk-namespace stuff.

2022-01-25 08:16 UTC, asuessenbach commented on framework/core/hpp_debug.h
> +	virtual void set_debug_name(VkDevice     device,
Will remove the virtuals.

2022-01-25 08:22 UTC, asuessenbach commented on framework/core/hpp_debug.h
> +	    cmd_begin_label(VkCommandBuffer command_buffer, const char *name, glm::vec4 color = {}) const override
Will remove the default on this function.
But I think, the other defaults in this file should be kept as they are (or the corresponding defaults in core/debug.h should be changed as well; I don't know how many adjustments that would provoke throughout the code base).

2022-01-25 08:24 UTC, asuessenbach commented on framework/core/hpp_device.h
> +	                requested_extensions)
Good point. Will do so.

2022-01-25 08:24 UTC, asuessenbach commented on framework/core/hpp_swapchain.h
> +	const vk::Extent2D &get_extent() const
For the same reason as above.

2022-01-25 08:27 UTC, asuessenbach commented on framework/hpp_api_vulkan_sample.h
> +	virtual void create_render_context(vkb::platform::HPPPlatform const &platform) override;
Will remove virtuals.

2022-01-25 08:37 UTC, asuessenbach commented on framework/hpp_gui.h
> +			pssci.push_back(*reinterpret_cast<VkPipelineShaderStageCreateInfo const *>(&ci));
Or to reserve the needed space, and still push_back.
No need for a counter variable, then.

2022-01-25 08:38 UTC, asuessenbach commented on framework/hpp_gui.h
> +	vkb::HPPDrawer &get_drawer()
Same reason as above.

2022-01-25 08:47 UTC, asuessenbach commented on framework/hpp_gui.h
> +	bool update_buffers()
Here, a simple using `vkb::Gui::update_buffers` did not work, as there's also a private `update_buffers` in `vkb::Gui`. Could not successfully compile then.

2022-01-25 08:59 UTC, asuessenbach commented on framework/hpp_vulkan_sample.cpp
> +		const auto &key_event = static_cast<const KeyInputEvent &>(input_event);
This line of code is an exact copy from vulkan_sample.cpp.
My understanding was, that the if-clause makes sure that the input_event in fact is a KeyInputEvent.

2022-01-25 09:00 UTC, asuessenbach commented on framework/hpp_vulkan_sample.cpp
> +			if (!vkb::common::graphs::generate_all(get_render_context(), *scene.get()))
Will remove it (in both hpp_vulkan_sample.cpp and vulkan_sample.cpp)

2022-01-25 09:11 UTC, asuessenbach commented on framework/hpp_vulkan_sample.cpp
> +void HPPVulkanSample::set_viewport_and_scissor(vkb::core::HPPCommandBuffer const &command_buffer, const vk::Extent2D &extent) const
Will make it static (in both, HPPVulkanSample and VulkanSample).

2022-01-25 09:13 UTC, asuessenbach commented on framework/hpp_vulkan_sample.cpp
> +	// To be overriden by sample
?

2022-01-25 09:28 UTC, asuessenbach commented on framework/hpp_vulkan_sample.h
> +	virtual bool prepare(vkb::platform::HPPPlatform &platform) override;
Adjusted in both hpp_vulkan_sample.h and vulkan_sample.h

2022-01-25 09:28 UTC, asuessenbach commented on framework/hpp_vulkan_sample.h
> +	virtual bool resize(const uint32_t width, const uint32_t height) override;
Adjusted in both hpp_vulkan_sample.h and vulkan_sample.h.

2022-01-25 10:01 UTC, asuessenbach commented on framework/platform/hpp_platform.h
> +	vkb::platform::HPPWindow &get_window()
As noted above, by intention.

2022-01-25 10:02 UTC, asuessenbach commented on framework/rendering/hpp_render_context.h
> +	vkb::core::HPPCommandBuffer &begin(vkb::CommandBuffer::ResetMode reset_mode = vkb::CommandBuffer::ResetMode::ResetPool)
By intention.

2022-01-25 10:02 UTC, asuessenbach commented on framework/rendering/hpp_render_context.h
> +	vkb::rendering::HPPRenderFrame &get_active_frame()
By intention

2022-01-25 10:02 UTC, asuessenbach commented on framework/rendering/hpp_render_frame.h
> +	vkb::rendering::HPPRenderTarget &get_render_target()
By intention.

2022-01-25 12:50 UTC, asuessenbach commented
Does anybody know how to resolve that failing Quality Check?

2022-01-25 17:23 UTC, gpx1000 commented on framework/common/hpp_strings.h
> +	return vkb::to_string(static_cast<VkExtent2D const &>(extent));
makes sense to me.

2022-01-25 17:40 UTC, gpx1000 commented
What it's having a problem with is the doxygen syntax.

in stats_common.h at line 31 it's calling a reference to the Stats object.  That doesn't look like it's resolving anymore.  My guess is one of the c++ includes is including this file which is making doxygen think that Stats isn't defined in the namespace it has knowledge of.  You might need to put vkb:: infront of Stats?  I haven't tested any of this so I don't know for sure and am operating totally off gut instinct.

2022-01-26 11:20 UTC, asuessenbach commented
Changing from `Stats` -> `vkb::Stats` resolved the first warning of the Quality Checks.
But how would I resolve the other two, complaining about `size_t` and `uint32_t`? Adding namespace `std::` does not help here.

2022-01-26 18:21 UTC, SaschaWillems commented
I'm actually wondering why the @ref is there. Afaik @ref can be used to link to other sections of the documentation (e.g. for custom types), but I'm not sure if it can be used on intrinsic types. I think you can safely remove the @ref and it should work.

2022-01-26 20:18 UTC, gpx1000 commented
I think @SaschaWillems  is correct.  it would be better to remove the ref directive from intrinsic types.  My guess is the problem is going to stem from size_t and uint32_t are defined as part of the std namespace in C++ as a type and in C which naturally doesn't have the std namespace, they are a normal POC type.  So doxygen is going to get confused when they are included in either direction (i.e. adding std:: will work in C++ to fix it but will break C).  The "real" fix if want to maintain the ref function is to set one vs the other depending upon language type with a check.  Probably the easiest way to "fix" it if we want to keep the ref is to copy/rename the file to .hpp extension and only include it in C++ files.  I think that's overkill for this problem so let's nuke the ref.  It's safe to assume people reading the doc knows what size_t and uint32_t are.
NB: a different solution would be to switch to a true POC type that both C and C++ share.  i.e. unsigned int for both.  It technically doesn't mean the same thing, but that would also fix it.

2022-02-08 07:58 UTC, asuessenbach commented
To rephrase my comment from two weeks ago: Is there anything I can do to get this PR approved?

2022-02-08 10:13 UTC, gary-sweet approved these changes

2022-02-08 17:51 UTC, gpx1000 approved these changes

2022-02-11 16:43 UTC, SaschaWillems approved these changes

2022-02-14 17:42 UTC, merged