Change vkb::core::HPPPhysicalDevice and vkb::core::HPPInstance from facades over vkb::PhysicalDevice and vkb::Instance, respectively, to self-contained classes using vulkan.hpp
KhronosGroup/Vulkan-Samples pull request #442
Opened 2022-04-12 12:32 UTC by asuessenbach

## Description

Replacing this part of the framework shows how to manage some more resources using vulkan.hpp.

In order to do so, minor adjustments in vkb::core::HPPDevice and framework/hpp_vulkan_sample.cpp were needed.

I have tested it on Window10 on nvidia HW.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

2022-04-14 21:07 UTC, gpx1000 approved these changes, later dismissed
LGTM

2022-04-18 10:39 UTC, SaschaWillems approved these changes, later dismissed
LGTM

2022-04-29 08:47 UTC, gary-sweet requested changes
I'm seeing some build errors with this change:

```
/usr/bin/ld: ../framework/lib/Debug/x86_64/libframework.a(hpp_device.cpp.o): in function `vk::PhysicalDevicePerformanceQueryFeaturesKHR& vkb::core::HPPPhysicalDevice::request_extension_features<vk::PhysicalDevicePerformanceQueryFeaturesKHR>()':
/build/gsweet/vc5_git/thirdparty_vulkan/Vulkan-Samples/framework/core/hpp_physical_device.h:113: undefined reference to `vk::PhysicalDevicePerformanceQueryFeaturesKHR::structureType'
/usr/bin/ld: /build/gsweet/vc5_git/thirdparty_vulkan/Vulkan-Samples/framework/core/hpp_physical_device.h:123: undefined reference to `vk::PhysicalDevicePerformanceQueryFeaturesKHR::structureType'
/usr/bin/ld: /build/gsweet/vc5_git/thirdparty_vulkan/Vulkan-Samples/framework/core/hpp_physical_device.h:126: undefined reference to `vk::PhysicalDevicePerformanceQueryFeaturesKHR::structureType'
/usr/bin/ld: ../framework/lib/Debug/x86_64/libframework.a(hpp_device.cpp.o): in function `vk::PhysicalDeviceHostQueryResetFeatures& vkb::core::HPPPhysicalDevice::request_extension_features<vk::PhysicalDeviceHostQueryResetFeatures>()':
/build/gsweet/vc5_git/thirdparty_vulkan/Vulkan-Samples/framework/core/hpp_physical_device.h:113: undefined reference to `vk::PhysicalDeviceHostQueryResetFeatures::structureType'
/usr/bin/ld: /build/gsweet/vc5_git/thirdparty_vulkan/Vulkan-Samples/framework/core/hpp_physical_device.h:123: undefined reference to `vk::PhysicalDeviceHostQueryResetFeatures::structureType'
/usr/bin/ld: /build/gsweet/vc5_git/thirdparty_vulkan/Vulkan-Samples/framework/core/hpp_physical_device.h:126: undefined reference to `vk::PhysicalDeviceHostQueryResetFeatures::structureType'
collect2: error: ld returned 1 exit status
```

2022-04-29 11:06 UTC, gary-sweet commented
The build errors appear to only happen in debug builds.

2022-05-02 09:15 UTC, asuessenbach commented
@gary-sweet Strange thing!
What compiler are you using?
Could you please verify, that you have this in your vulkan_structs.hpp:
```
  struct PhysicalDevicePerformanceQueryFeaturesKHR
  {
    using NativeType = VkPhysicalDevicePerformanceQueryFeaturesKHR;

    static const bool                                  allowDuplicate = false;
    static VULKAN_HPP_CONST_OR_CONSTEXPR StructureType structureType  = StructureType::ePhysicalDevicePerformanceQueryFeaturesKHR;
```
I don't see, where that could be different in release and debug builds. And I don't get any errors with MSVC 2022, neither release nor debug.
Could you slightly modify that struct in vulkan_structs.hpp, by
- replacing that `VULKAN_HPP_CONST_OR_CONSTEXPR` in front of the `StructureType` by a simple `const`?
- adding `VULKAN_HPP_NAMESPACE::` in front of the two `StructureType`s in that line?
Does that change anything?

2022-05-03 08:08 UTC, gary-sweet commented
This is happening on Linux on both cross-compiled gcc 8.3 and native gcc 9.4.
I'll do some more digging to see if I can find the cause.

2022-05-03 09:20 UTC, asuessenbach commented
@gary-sweet Please try a static_cast to the call in hpp_physical_device.h, on line 113, like this:
`		auto extension_features_it = extension_features.find(static_cast<vk::StructureType>(HPPStructureType::structureType));
`

2022-05-03 09:25 UTC, gary-sweet commented
> @gary-sweet Please try a static_cast to the call in hpp_physical_device.h, on line 113, like this: ` auto extension_features_it = extension_features.find(static_cast<vk::StructureType>(HPPStructureType::structureType)); `

No change sadly.

2022-05-03 09:37 UTC, asuessenbach commented
@gary-sweet Does it change anything, if you're compiling with -std=c++17 ?
Then, that `structureType` would be a `constexpr`, instead of just a `const`.

2022-05-03 09:53 UTC, asuessenbach commented
@gary-sweet And another thing I'd like you to try:
```
		vk::StructureType structureType         = HPPStructureType::structureType;
		auto              extension_features_it = extension_features.find(structureType);
```

2022-05-03 10:22 UTC, gary-sweet commented
> @gary-sweet Does it change anything, if you're compiling with -std=c++17 ? Then, that `structureType` would be a `constexpr`, instead of just a `const`.

No difference with c++17

2022-05-03 10:30 UTC, gary-sweet commented
> @gary-sweet And another thing I'd like you to try:
> 
> ```
> 		vk::StructureType structureType         = HPPStructureType::structureType;
> 		auto              extension_features_it = extension_features.find(structureType);
> ```

Also no change I'm afraid.
I'll keep digging here.

2022-05-04 08:04 UTC, asuessenbach commented
@gary-sweet Just to be sure...
The things I suggested to fix the build failures were supposed to fix just the first one out of three (identical issues). I'm sure you realized that, but I just wanted to make sure.
(You see: I'm really running out of ideas!)

2022-05-05 08:28 UTC, gary-sweet commented
> @gary-sweet Just to be sure... The things I suggested to fix the build failures were supposed to fix just the first one out of three (identical issues). I'm sure you realized that, but I just wanted to make sure. (You see: I'm really running out of ideas!)

Yes, I was aware, thanks. I'm OOO for a couple of days, but will circle back to this when I return.

2022-05-09 10:29 UTC, gary-sweet commented
Is someone else able to try a debug build of this on Linux?
I get the same result when building with clang as I do with various versions of gcc.

Would be good to know if it's just a problem locally, or if others can reproduce.

2022-05-09 11:18 UTC, gary-sweet commented
Well, I'm mystified. I can only think that we're hitting a compiler or linker bug.

If I add methods to return `structureType` instead of accessing it directly in `request_extension_features(`) then it links ok.

This works for example:

```
  struct PhysicalDeviceHostQueryResetFeatures
  {
    using NativeType = VkPhysicalDeviceHostQueryResetFeatures;

    static const bool                                  allowDuplicate = false;
    static VULKAN_HPP_CONST_OR_CONSTEXPR StructureType structureType =
      StructureType::ePhysicalDeviceHostQueryResetFeatures;

    static VULKAN_HPP_CONST_OR_CONSTEXPR StructureType ST() { return structureType; }
    ....
```

2022-05-09 11:31 UTC, SaschaWillems commented
This builds fine for me on my Ubuntu 18 based system with a (seemingly) outdated GCC 7.5.
 
P.S. : Build times on Linux are horrible. A clean build took ~ 45 Minutes on my Laptop :(

2022-05-09 11:32 UTC, gary-sweet commented
> This builds fine for me on my Ubuntu 18 based system with a (seemingly) outdated GCC 7.5.
> 
> P.S. : Build times on Linux are horrible. A clean build took ~ 45 Minutes on my Laptop :(

And that was definitely a debug build?

2022-05-09 12:10 UTC, SaschaWillems commented
I ran the following command:

```cmake --build build/linux --config Debug --target vulkan_samples -- -j4```

So I think it should've been a debug build. Or is there any other way I need to force that?

2022-05-09 13:22 UTC, gary-sweet commented
> I ran the following command:
> 
> `cmake --build build/linux --config Debug --target vulkan_samples -- -j4`
> 
> So I think it should've been a debug build. Or is there any other way I need to force that?

So, I ran that very command myself and it linked ok. Setting the CMAKE_BUILD_TYPE explicitly to Debug in cmake-gui and then running the same command fails however. I don't think your command is actually building debug for some reason.

2022-05-09 13:24 UTC, gary-sweet commented
> > I ran the following command:
> > `cmake --build build/linux --config Debug --target vulkan_samples -- -j4`
> > So I think it should've been a debug build. Or is there any other way I need to force that?
> 
> So, I ran that very command myself and it linked ok. Setting the CMAKE_BUILD_TYPE explicitly to Debug in cmake-gui and then running the same command fails however. I don't think your command is actually building debug for some reason.

This probably explains why:

"If the build tool isn't multi-config (like gcc), then the --config argument is ignored. Instead the build type is set via the CMAKE_BUILD_TYPE CMake variable; i.e. it's set when running CMake, not when running the build tool."

2022-05-09 15:48 UTC, SaschaWillems commented
You're right. Setting CMAKE_BUILD_TYPE to Debug the build fails for me too with the same message you posted above.

2022-05-09 16:06 UTC, gpx1000 commented
Yep, it fails here too.  It *looks* like it's having problems figuring out what StructureType is as a type.  Not sure why, it'd take a bit more debugging to figure out why for me.  However, I have a silly stupid solution that works here.
at line 104 change the signature to pass in the StructureType:
HPPStructureType &request_extension_features(vk::StructureType type)

then use type everywhere in the function (line 113, 123, 126).

Finally in hpp_device line 102-103 add in vk::PhysicalDevicePerformanceQueryFeaturesKHR::structureType and vk::PhysicalDeviceHostQueryResetFeatures::structureType to the passed in parameters.

Doing that it will build/link fine.  It's about as silly, stupid workaround as it gets, but hey, why work too hard?

2022-05-10 07:12 UTC, asuessenbach commented
> HPPStructureType &request_extension_features(vk::StructureType type)

Essentially, that should work. But it would remove the advantage you've got using vulkan.hpp.
After all, passing in the structure type to get via both, the template argument and the function argument is redundant. In vulkan.h, you don't have any connection between the actual structure type and corresponding value of type VkStructureType. But in vulkan.hpp, you have that. And therefore, such a redundant calling pattern feels wrong.

2022-05-10 08:02 UTC, gary-sweet commented
> > HPPStructureType &request_extension_features(vk::StructureType type)
> 
> Essentially, that should work. But it would remove the advantage you've got using vulkan.hpp. After all, passing in the structure type to get via both, the template argument and the function argument is redundant. In vulkan.h, you don't have any connection between the actual structure type and corresponding value of type VkStructureType. But in vulkan.hpp, you have that. And therefore, such a redundant calling pattern feels wrong.

Wrapping access to `structureType` in a static method also worked for me. That doesn't require passing any redundant arguments. `structureType` could be made private to ensure the accessor was always used. It's obviously not trivial, but nothing else I tried worked.

2022-05-10 08:06 UTC, gary-sweet commented
> > > HPPStructureType &request_extension_features(vk::StructureType type)
> > 
> > 
> > Essentially, that should work. But it would remove the advantage you've got using vulkan.hpp. After all, passing in the structure type to get via both, the template argument and the function argument is redundant. In vulkan.h, you don't have any connection between the actual structure type and corresponding value of type VkStructureType. But in vulkan.hpp, you have that. And therefore, such a redundant calling pattern feels wrong.
> 
> Wrapping access to `structureType` in a static method also worked for me. That doesn't require passing any redundant arguments. `structureType` could be made private to ensure the accessor was always used. It's obviously not trivial, but nothing else I tried worked.

Steven's suggestion is obviously much simpler and doesn't affect the hpp api's at all, just the framework, so I'd probably be leaning towards that personally.

2022-05-10 08:12 UTC, gpx1000 commented
I'm doing this from my phone as it's 1am here, but I had a thought.
Someone try inlining the template function.  I know it sounds silly, but I
have a feeling it has to do with the optimizations are inlining
automatically while the debug version isn't.  This results in violating the
one definition rule.

Other options include explicit template specialization.  Either should not
involve changes to the underlining header files.

On Tue, May 10, 2022, 1:06 AM Gary Sweet ***@***.***> wrote:

> HPPStructureType &request_extension_features(vk::StructureType type)
>
> Essentially, that should work. But it would remove the advantage you've
> got using vulkan.hpp. After all, passing in the structure type to get via
> both, the template argument and the function argument is redundant. In
> vulkan.h, you don't have any connection between the actual structure type
> and corresponding value of type VkStructureType. But in vulkan.hpp, you
> have that. And therefore, such a redundant calling pattern feels wrong.
>
> Wrapping access to structureType in a static method also worked for me.
> That doesn't require passing any redundant arguments. structureType could
> be made private to ensure the accessor was always used. It's obviously not
> trivial, but nothing else I tried worked.
>
> Steven's suggestion is obviously much simpler and doesn't affect the hpp
> api's at all, just the framework, so I'd probably be leaning towards that
> personally.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KhronosGroup/Vulkan-Samples/pull/442#issuecomment-1122064546>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA5IAY3AW2LQZF4PNOMAMBDVJIKIDANCNFSM5THFCQPA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-05-10 08:18 UTC, gary-sweet commented
> I'm doing this from my phone as it's 1am here, but I had a thought. Someone try inlining the template function. I know it sounds silly, but I have a feeling it has to do with the optimizations are inlining automatically while the debug version isn't. This results in violating the one definition rule. Other options include explicit template specialization. Either should not involve changes to the underlining header files.
> […](#)
> On Tue, May 10, 2022, 1:06 AM Gary Sweet ***@***.***> wrote: HPPStructureType &request_extension_features(vk::StructureType type) Essentially, that should work. But it would remove the advantage you've got using vulkan.hpp. After all, passing in the structure type to get via both, the template argument and the function argument is redundant. In vulkan.h, you don't have any connection between the actual structure type and corresponding value of type VkStructureType. But in vulkan.hpp, you have that. And therefore, such a redundant calling pattern feels wrong. Wrapping access to structureType in a static method also worked for me. That doesn't require passing any redundant arguments. structureType could be made private to ensure the accessor was always used. It's obviously not trivial, but nothing else I tried worked. Steven's suggestion is obviously much simpler and doesn't affect the hpp api's at all, just the framework, so I'd probably be leaning towards that personally. — Reply to this email directly, view it on GitHub <[#442 (comment)](https://github.com/KhronosGroup/Vulkan-Samples/pull/442#issuecomment-1122064546)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA5IAY3AW2LQZF4PNOMAMBDVJIKIDANCNFSM5THFCQPA> . You are receiving this because you commented.Message ID: ***@***.***>

No luck with inlining request_extension_features() sadly - same link errors.

2022-05-10 09:03 UTC, gary-sweet commented
>Other options include explicit template specialization.

That isn't possible in this case since these are class methods, which aren't at namespace scope. I believe C++17 would be needed for that (we are stuck on C++11 for a while yet).

2022-05-10 09:55 UTC, asuessenbach commented
I've created a very downsized version of this problem (https://godbolt.org/z/qfc3a9YTr), reproducing this compilation error.
But with that "repro", two of the approaches I suggested above would resolve that error.
Maybe someone could try to extend that snippet such that those approaches don't help anymore?

2022-05-10 10:15 UTC, gary-sweet commented
> I've created a very downsized version of this problem (https://godbolt.org/z/qfc3a9YTr), reproducing this compilation error. But with that "repro", two of the approaches I suggested above would resolve that error. Maybe someone could try to extend that snippet such that those approaches don't help anymore?

Well, I know I tried option one before and still got failures, but having tried it again it appears to work just fine. No idea how I managed to screw that up the first time around, but apologies to everyone that has spent any time on this since then!

At least we have a trivial workaround though.

2022-05-10 10:27 UTC, gary-sweet commented
Here's an explanation of the issue that Andreas found:

https://stackoverflow.com/questions/5391973/undefined-reference-to-static-const-int

2022-05-10 11:14 UTC, gary-sweet approved these changes
Thanks, LGTM

2022-05-10 11:57 UTC, asuessenbach commented
Well, after this compile issue (hopefully) is ruled out, we should consider to have some debug builds as part of the CI checks !

2022-05-10 13:55 UTC, gpx1000 approved these changes
good sluething.  Glad this worked out.

LGTM!

2022-05-18 18:36 UTC, SaschaWillems approved these changes

2022-05-19 06:01 UTC, asuessenbach commented
Now, that there are three approvals on this PR... may I just merge it?

2022-05-19 09:18 UTC, TomAtkinsonArm commented
> Now, that there are three approvals on this PR... may I just merge it?

@marty-johnson59

2022-05-19 09:21 UTC, TomAtkinsonArm approved these changes
LGTM

2022-05-19 14:34 UTC, merged