Add new sample for graphics pipeline libraries
KhronosGroup/Vulkan-Samples pull request #445
Opened 2022-04-18 09:54 UTC by SaschaWillems

## Description

This PR adds a sample for the new `VK_EXT_graphics_pipeline_library` extension. The sample creates a pipeline library for shared pipeline state parts and reuses this to generate randomized fragment shaders in a background thread. The sample also includes a small tutorial.

I have tested the sample on Windows 10 with an NVIDIA RTX 2060 and recent Vulkan developer driver.

Fixes #441

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

2022-04-27 13:38 UTC, marty-johnson59 commented
Added reviewer suggestions.  Would be great if we could get the DT folks (@aurolou. @mklefrancois) to review as I believe that's the target for this EXT.  Thanks!

2022-04-29 11:24 UTC, gary-sweet reviewed
Builds ok for me, and correctly reports that the required extensions are not supported, but that's all I can test I'm afraid.

2022-05-02 18:41 UTC, gpx1000 approved these changes, later dismissed
works well here Linux

2022-05-09 14:56 UTC, TomAtkinsonArm reviewed
Small typo. Extension not supported, I will update graphics drivers and try again

2022-05-09 14:56 UTC, TomAtkinsonArm commented on samples/README.md
> +Uses the graphics pipeline library extensions to improve run-time pipeline creation. Instead of creating the whole pipeline at once, this sample makes use of that extension to pre-built shared pipeli
`pre-built shared pipeline parts like like vertex input state`

to

`pre-build shared pipeline parts like vertex input state`

2022-05-09 16:18 UTC, SaschaWillems commented on samples/README.md
> +Uses the graphics pipeline library extensions to improve run-time pipeline creation. Instead of creating the whole pipeline at once, this sample makes use of that extension to pre-built shared pipeli
Thanks for spotting this. I have pushed a change to fix this.

2022-05-16 05:51 UTC, gpx1000 approved these changes, later dismissed

2022-05-16 16:21 UTC, Tobski requested changes
Mostly LGTM, some minor comments and one suggested modification.

2022-05-16 16:21 UTC, Tobski commented on samples/extensions/graphics_pipeline_library/README.md
> +A note on `VK_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT`: This is an optimization flag. If specified, implementations are allowed to do additional optimization passes. This may increase build ti
I'd suggest it's worth mentioning here that we suggest apps build first without this flag, and then build again with this flag enabled on the slow path, and switch it out for the fast-linked version when available.

2022-05-16 16:21 UTC, Tobski commented on samples/extensions/graphics_pipeline_library/graphics_pipeline_library.cpp
> +// Compiling shaders can be simplified with the new extension, so we only require code to generate the SPIR-V in thhis sample
```suggestion
// Compiling shaders can be simplified with the new extension, so we only require code to generate the SPIR-V in this sample
```

2022-05-16 16:21 UTC, Tobski commented on samples/extensions/graphics_pipeline_library/README.md
> +With the new extension it's now possible to separate the monolithic pipeline state into multiple parts that can be r-used and built independently. This opens up new possibilities for optimizing pipel
```suggestion
With the new extension it's now possible to separate the monolithic pipeline state into multiple parts that can be reused and built independently. This opens up new possibilities for optimizing pipeline creation and reducing hitches at runtime.
```

Hitches is usually the term used by most ISVs I've heard.

2022-05-16 16:21 UTC, Tobski commented on samples/extensions/graphics_pipeline_library/README.md
> +A note on `VK_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT`: This is an optimization flag. If specified, implementations are allowed to do additional optimization passes. This may increase build ti
I also wonder if it's worth making the sample behave like this? The pieces to do it are all there, so I don't think it'd be a big change.

2022-05-18 18:11 UTC, SaschaWillems commented on samples/extensions/graphics_pipeline_library/README.md
> +A note on `VK_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT`: This is an optimization flag. If specified, implementations are allowed to do additional optimization passes. This may increase build ti
That's indeed a good point. I don't want the sample to become too complicated, so would it be okay if there was a checkbox in the UI where the optimization flag can be toggled? That would let people actually see the difference in build time very easily.

2022-05-19 08:57 UTC, Tobski commented on samples/extensions/graphics_pipeline_library/README.md
> +A note on `VK_PIPELINE_CREATE_LINK_TIME_OPTIMIZATION_BIT_EXT`: This is an optimization flag. If specified, implementations are allowed to do additional optimization passes. This may increase build ti
That's probably a reasonable compromise.

2022-05-22 06:49 UTC, SaschaWillems commented
@Tobski: Thank you very much for your valuable feedback. I have updated the sample and added an UI toggle for the link time optimization flag and also fixed the readme.

2022-05-23 21:07 UTC, pdaniell-nv requested changes

2022-05-23 21:07 UTC, pdaniell-nv commented on samples/extensions/graphics_pipeline_library/graphics_pipeline_library.cpp
> +	executable_pipeline_create_info.pNext = &linking_info;
executable_pipeline_create_info.layout must not be left NULL see https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-flags-06729 and https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-flags-06730. This came about due a recent spec change: https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5164

2022-05-24 10:20 UTC, TomAtkinsonArm requested changes
LGTM - A tiny typo I missed earlier. Cant run as my devices do not support the extension

2022-05-24 10:20 UTC, TomAtkinsonArm commented on samples/README.md
> +Uses the graphics pipeline library extensions to improve run-time pipeline creation. Instead of creating the whole pipeline at once, this sample makes use of that extension to pre-build shared pipeli
`like like` -> `such as`

2022-05-24 17:08 UTC, SaschaWillems commented on samples/extensions/graphics_pipeline_library/graphics_pipeline_library.cpp
> +	executable_pipeline_create_info.pNext = &linking_info;
Thanks for pointing that out. I have updated the sample accordingly.

2022-05-24 17:10 UTC, SaschaWillems commented on samples/README.md
> +Uses the graphics pipeline library extensions to improve run-time pipeline creation. Instead of creating the whole pipeline at once, this sample makes use of that extension to pre-build shared pipeli
Thanks for pointing this out. Fixed it.

2022-05-24 18:04 UTC, pdaniell-nv approved these changes

2022-06-01 17:05 UTC, marty-johnson59 commented
@SaschaWillems, this has now  had approvals from Tobias, Piers and Steve (tho some are stale).  Looks like all threads are resolved now?  Are we ready to merge?

2022-06-01 18:16 UTC, SaschaWillems commented
Yes, feel free to merge :)

2022-06-01 18:38 UTC, merged