Add conditional rendering example
KhronosGroup/Vulkan-Samples pull request #472
Opened 2022-06-05 12:41 UTC by SaschaWillems

## Description

This PR adds a new example for the `VK_EXT_conditional_rendering` extension. With this extension one can conditionally disable draw and dispatch commands based on a dedicated buffer. The sample render a complex glTF sample and uses such a conditional buffer to toggle visibility for the glTF's scene nodes based on user input.

The sample also includes a tutorial in the readme.

**Important note**: I had to make a slight change to remove a conjugation of the rotation from one of the frameworks components (see [here](https://github.com/KhronosGroup/Vulkan-Samples/compare/master...SaschaWillems:conditional_render?expand=1#diff-4746ae3da524d8cc63f4e454636e84d0a00cd31b3f3111a941da474c8d91d367L87)). Initially, with this conjugation in place, the new glTF model did not display properly. Removing it fixed this and I tested all other samples to make sure that this didn't break any of the other glTF's used in this repo.

**Important note**: This sample requires new assets, so https://github.com/KhronosGroup/Vulkan-Samples-Assets/pull/17 needs to be merged first.

Sample was tested on Windows 10 and an NVIDIA RTX 2060.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

2022-06-21 08:13 UTC, TomAtkinsonArm requested changes
Small change requested

Other than this it LGTM!! Its pretty fun to toggle different meshes on and off

2022-06-21 08:13 UTC, TomAtkinsonArm commented on samples/extensions/conditional_rendering/CMakeLists.txt
> +    DESCRIPTION "todo"
We can copy and paste the description from the samples readme here?

2022-06-21 10:27 UTC, asuessenbach commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +		VkClearValue clear_values[2];
No need to have that clear_values inside the loop again, can use that one from above.

2022-06-21 10:27 UTC, asuessenbach commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +		VkRenderPassBeginInfo render_pass_begin_info    = vkb::initializers::render_pass_begin_info();
No need to have a new render_pass_begin_info here, can use that one from above. The only part that changes per loop iteration is the framebuffers[i].

2022-06-21 10:27 UTC, asuessenbach commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +			glm::mat4 node_transform = node.node->get_transform().get_world_matrix();
I would move all those local variables (node_transform, offsets, ..., mat) closer to where they're used below, maybe not even needing a local variable.

2022-06-21 10:27 UTC, asuessenbach commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +	uniform_data.view       = glm::scale(uniform_data.view, glm::vec3(0.1f, -0.1f, 0.1f));
Why do you multiply camera.matrices.view with the identity, and scale it in a separate step?

2022-06-21 10:27 UTC, asuessenbach commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +			}
Use std::fill() instead?

2022-06-21 10:27 UTC, asuessenbach commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +			update_visibility_buffer();
Use std::fill() instead?

2022-06-21 10:27 UTC, asuessenbach commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +		vkDestroyDescriptorSetLayout(get_device().get_handle(), descriptor_set_layout, nullptr);
Where is the descriptor_set freed?

2022-06-21 10:27 UTC, asuessenbach commented on shaders/conditional_rendering/model.vert
> +	outNormal = inNormal;
No need to set outNormal here.

2022-06-21 18:30 UTC, SaschaWillems commented on samples/extensions/conditional_rendering/CMakeLists.txt
> +    DESCRIPTION "todo"
Good catch. Should do a search for "todo" in the future before submitting new PRs ^^

2022-06-21 18:30 UTC, SaschaWillems commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +		VkClearValue clear_values[2];
Good catch. Dunno why I duplicated this.

2022-06-21 18:31 UTC, SaschaWillems commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +		VkRenderPassBeginInfo render_pass_begin_info    = vkb::initializers::render_pass_begin_info();
Same as above. Thanks for noticing.

2022-06-21 18:35 UTC, SaschaWillems commented on shaders/conditional_rendering/model.vert
> +	outNormal = inNormal;
Good catch. That line is indeed not necessary at all.

2022-06-21 18:44 UTC, SaschaWillems commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +			glm::mat4 node_transform = node.node->get_transform().get_world_matrix();
Good point. Will change that.

2022-06-21 18:52 UTC, SaschaWillems commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +			}
Good idea. Will use std:fill in here.

2022-06-21 18:52 UTC, SaschaWillems commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +			update_visibility_buffer();
Same as above, will move to std::fill.

2022-06-21 18:55 UTC, SaschaWillems commented on samples/extensions/conditional_rendering/conditional_rendering.cpp
> +	uniform_data.view       = glm::scale(uniform_data.view, glm::vec3(0.1f, -0.1f, 0.1f));
Good question. Will combine the two steps.

2022-06-23 08:30 UTC, asuessenbach approved these changes

2022-06-23 18:12 UTC, gpx1000 approved these changes
LGTM

2022-07-06 11:41 UTC, gary-sweet reviewed
Doesn't break anything for me, and correctly reports that the extension is not supported.
Can't really add an approval given that I can't test the actual code though.

2022-07-06 17:30 UTC, marty-johnson59 commented on samples/extensions/conditional_rendering/CMakeLists.txt
> +    DESCRIPTION "todo"
Is this resolved now?  are we good to merge?

2022-07-07 05:54 UTC, SaschaWillems commented on samples/extensions/conditional_rendering/CMakeLists.txt
> +    DESCRIPTION "todo"
Yes, I have since then added a proper description, so this has been resolved.

2022-07-08 15:42 UTC, marty-johnson59 commented on samples/extensions/conditional_rendering/CMakeLists.txt
> +    DESCRIPTION "todo"
OK, sounds good.  Then should be safe to assume we have Tom's approval as well - I'll merge.  Thanks!

2022-07-08 15:43 UTC, merged