calibrated timestamps sample
KhronosGroup/Vulkan-Samples pull request #608
Opened 2023-01-28 00:30 UTC by gpx1000

## Description

Add a sample showing how to use Calibrated Timestamps in an existing sample.

Fixes #<issue number>

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

2023-02-01 12:32 UTC, asuessenbach reviewed
Although I'm not a native speaker, I think the readme.md needs some substantial word-smithing.

Besides that, my understanding of the time domains is a bit different than yours. I think, there's nothing like an "optimal" time domain. There is one device time domain and one (Windows) or two (Linux) host device domains. They are not better or worse, they are different domains.
For the device time domain, you need `VkQueueFamilyProperties::timestampValidBits` and `VkPhysicalDeviceLimits::timestampPeriod` to determine nanoseconds.
While the two linux time domains already are in nanoseconds, you need the result from the windows function `QueryPerformanceFrequency` for the windows time domain to get from ticks to seconds.
Finally, the maxDeviation values could be used, somehow, to asses the quality of the actual time stamps.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +	bool                         isTimeDomainUpdated = false;        // this is just to tell if time domain update has a VK_SUCCESS in the end
I think, the naming convention for member variables is camel_case here. That is, isTimeDomainUpdated should probably be named is_time_domain_updated.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +	bool                         isTimestampUpdated  = false;        // this is just to tell the GUI whether timestamps operation has a VK_SUCCESS in the end
isTimestampUpdated -> is_timestamp_updated

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +	uint32_t                     time_domain_count   = 0;
Why do you need `time_domain_count`? It's just the `time_domains.size()`.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +		VkImage        image{};
Why do you initialize some handles with `= VK_NULL_HANDLE`, and others with `{}`?

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +	// MODs:
`MODs:` ?

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +	void               init_timeDomains_and_timestamps();                        // this initializes all time domain and timestamps related variables, vectors, and booleans
`init_timeDomains_and_timestamps` -> `init_time_domains_and_timestamps`

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +	void               toc(const std::string &input_tag = "Untagged");           // this marks the timestamp ends and updates the delta_timestamps
I like the naming of `tic()` and `toc()`. But maybe something like `timestamp_begin()` and `timestamp_end()` is more descriptive?

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +	render_pass_begin_info_0.pClearValues          = clear_values_0.data();
`render_pass_begin_info_0` and `clear_values_0` are never used.
Can be removed.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +	toc("Creating Command Buffer");
This section does not measure the creation of a command buffer but just the initialization of some structs.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +	tic("Draw Command Buffer");
This section does not measure the drawing of a command buffer, but the recording/building of some command buffers.
You should either change the tags for both measurements, or do just one measurement over the complete `build_command_buffers` function, maybe tagging as "Build Command Buffers"?

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +			render_pass_begin_info_1.clearValueCount          = 3;
Maybe better than plain `3`: `static_cast<uint32_t>(clear_values_1.size())`

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +			render_pass_begin_info.clearValueCount          = 1;
Why do you specify two `clear_values`, but use just one?

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +			render_pass_begin_info.clearValueCount          = 2;
Maybe better than plain `2`, again: `static_cast<uint32_t>(clear_values.size())`

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +{
The current version of the HDR sample uses some algorithm to determine the color format. You should use that here as well.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		render_pass_create_info.dependencyCount        = 2;
Maybe better than plain `2`: `static_cast<uint32_t>(dependencies.size())`

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		offscreen.height = static_cast<int>(height);
You should cast to `int32_t`, not to `int`.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		filter_pass.height = static_cast<int>(height);
You should cast to `int32_t`, not to `int`.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +	color_blend_state.attachmentCount = 1;
`1` -> `static_cast<uint32_t>(blend_attachment_states.size())`

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +std::string CalibratedTimestamps::read_time_domain(VkTimeDomainEXT inputTimeDomain)
This function does not read anything, but gets you a string. I would call it `to_string`.
Morevover, it's just a local helper function, that does not need to be a member function of `CalibratedTimestamps`.

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +void CalibratedTimestamps::update_time_domains()
This function just gets you the supported time domains. Maybe just name it `get_time_domains`?
Moreover, are those time domains supposed to vary over time? Why do you call it on every `tic` and `toc`?

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +void CalibratedTimestamps::update_timestamps()
I would call this function `get_timestamps`

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		uint64_t optimal_maxDeviation = *std::min_element(max_deviations.begin(), max_deviations.end());
std::min_element gets you the iterator. You don't need to find it again

2023-02-01 12:32 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		if (iterator_optimal != max_deviations.end())
... and, as long as there's at least one elment, the iterator will never be the `end()`. No need to check that.

2023-02-16 18:13 UTC, SaschaWillems commented
This crashes for me at runtime in the `timestamps_begin` function in the following line:

![image](https://user-images.githubusercontent.com/10283127/219451613-5a8f5048-86bc-47d8-876e-3caba4ec4b71.png)

The `timestamps.clear()` there looks wrong, as that vector is then never resized and always has zero elements

2023-02-16 18:14 UTC, SaschaWillems requested changes
See my comment, the sample doesn't work for me at all.

2023-02-21 10:44 UTC, JeremyG2101 commented
> This crashes for me at runtime in the `timestamps_begin` function in the following line:
> 
> ![image](https://user-images.githubusercontent.com/10283127/219451613-5a8f5048-86bc-47d8-876e-3caba4ec4b71.png)
> 
> The `timestamps.clear()` there looks wrong, as that vector is then never resized and always has zero elements
> 
> Same for `timestamps_end`. The vector is cleared here too and never resized before it's accessed.

Ohh! I forgot to recall that timestamps vector must  be resized and then pass its reference/data to vkGetCalibratedTimestampsEXT.. And for some reason it doesn't crush from my end...
But you are right! Good catch and thanks!

2023-02-27 22:34 UTC, gpx1000 commented
This PR is ready for review.

2023-03-13 06:16 UTC, SaschaWillems submitted a review, later dismissed

2023-03-21 18:31 UTC, asuessenbach reviewed
This sample just shows how to use the CalibratedTimestamps functions. If that was your goal, I'm fine with it.
But I see three possible improvements:
- With the `std::vector<DeltaTimestamp> delta_timestamps`, you are prepared to take multiple timestamps per frame. But you don't do it. Maybe you should consider adding one or more additional timestamps?
- You explicitly select the device domain, but measure the recording (or building) of a command buffer, which probably happens completely on the host. Maybe you should measure some device work, instead, like drawing or buffer uploading?
- You don't show any use of the deviations. Maybe at least displaying it could get you some feeling on what they are?

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		VkResult result = vkGetCalibratedTimestampsEXT(get_device().get_handle(), time_domains.size(), timestamps_info.data(), timestamps.data(), max_deviations.data());
Please `static_cast<uint32_t>(time_domains.size())`

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +			render_pass_begin_info_1.pClearValues             = clear_values_1.data();
Maybe move clear_values_1 and render_pass_begin_info_1 out of the loop.

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +			clear_value.depthStencil = {0.0f, 0};
`VkClearValue` is a union; setting `depthStencil` overwrites the `color`.
You should probably stay with the `color`.

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		subpass.colorAttachmentCount    = 2;
`2` -> `static_cast<uint32_t>(color_references.size())`

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		subpass.colorAttachmentCount = 1;
`1` -> `static_cast<uint32_t>(color_references.size())`

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		time_domains.clear();
No need to clear `time_domains`, as this is called just once.

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		time_domains.resize(static_cast<int>(time_domain_count));        // this needs static cast to int
Why should you need to cast `time_domain_count` to `int`?

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		max_deviations.resize(static_cast<int>(time_domain_count));
No need to `static_cast<int>` here

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +	is_time_domain_updated = ((result == VK_SUCCESS) && (time_domain_count > 0));
`is_time_domain_updated` sounds like if it is, well, updated, regularly, after some amount of time.
But it is just that everything is initialized/prepared once to actually get the data.

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		is_timestamp_updated = (result == VK_SUCCESS);
Maybe change this function to return a bool `(result == VK_SUCCESS)`.
No need to have that `is_timestamp_updated` anymore.

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +void CalibratedTimestamps::init_time_domains_and_timestamps()
Is this function useful at all?
It's just some one-time member variable initialization.

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		// Naming the tic-toc tags and begin timestamp for this particular mark
tic-toc ?

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		// Push back this partially filled element to the vector, which will be filled in its corresponding toc
toc ?

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +		void get_delta()
Is this really worth a function?
If at all, it doesn't get you anything (returning void) but calculates something. So `calculate_delta` or `determine_delta` would be a better fit.

2023-03-21 18:31 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.h
> +	struct
Some structs are named, others are not.
Is there a rationale behind that?

2023-03-22 00:41 UTC, gpx1000 commented
I tend to agree this sample doesn't fully exercise calibrated timestamps.  However, it does a fairly good job of demonstrating how to use them which I think is a decent goal.  I'll have Jeremy do another pass at increasing the scope a little bit more.  My only concern is about ensuring this sample's core is to teach specifically how to do calibrated timestamps and not get too complex to ultimately be useful.  Thanks for the review!

2023-03-22 08:52 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		subpass.colorAttachmentCount = 1;
You had marked this as resolved without any change. Do you want to keep it like this? If so, why?

2023-03-22 08:54 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		time_domains.resize(static_cast<int>(time_domain_count));        // this needs static cast to int
You should as well remove the comment.

2023-03-22 08:55 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +	is_time_domain_updated = ((result == VK_SUCCESS) && (time_domain_count > 0));
You should as well adjust the comment.

2023-03-22 09:08 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		render_pass_create_info.subpassCount           = static_cast<uint32_t>(color_references.size());
the subpassCount is not related to the number of color_references! Keep the `1` here.

2023-03-22 09:08 UTC, asuessenbach commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
One could go even further here, and move all the `VkClearValue`s, `VkRenderPassBeginInfo`s, `VkViewport`s, and `VkRect2D`s out of the loop, renaming them for example to `offscreen*`, `bloom*` or `filter_pass*`, and `framebuffer*`.
Would make the actual recording loop very short and clear.

2023-03-22 15:34 UTC, gpx1000 commented on samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
> +		subpass.colorAttachmentCount = 1;
that's my fault; I could have sworn I got it but I definitely missed it.

2023-03-26 07:33 UTC, SaschaWillems approved these changes, later dismissed

2023-04-03 15:08 UTC, asuessenbach approved these changes

2023-04-14 14:25 UTC, gary-sweet approved these changes
I just added calibrated timestamp support to my driver, so was actually able to test this.

2023-04-14 17:37 UTC, SaschaWillems approved these changes

2023-04-20 15:38 UTC, marty-johnson59 commented
Merging w/ 3 approvals

2023-04-20 15:38 UTC, merged