Changed all calls to std::vector::at() to std::vector::operator[], added assertions to check access, if appropriate.
KhronosGroup/Vulkan-Samples pull request #611
Opened 2023-02-01 16:29 UTC by asuessenbach

Fixes #577

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

2023-02-04 22:17 UTC, tomadamatkinson approved these changes, later dismissed

2023-02-05 08:58 UTC, SaschaWillems approved these changes, later dismissed
LGTM

2023-02-13 11:59 UTC, gary-sweet requested changes
The command_buffer_usage sample asserts for me with this change:

command_buffer_usage.cpp:259: void CommandBufferUsage::ForwardSubpassSecondary::record_draw(vkb::CommandBuffer&, const std::vector<std::pair<vkb::sg::Node*, vkb::sg::SubMesh*> >&, uint32_t, uint32_t, size_t): Assertion `mesh_end < nodes.size()' failed.
Aborted

2023-02-13 14:39 UTC, gary-sweet approved these changes

2023-02-13 16:14 UTC, merged