Change external_files_dir logic and permission logic.
KhronosGroup/Vulkan-Samples pull request #678
Opened 2023-04-25 05:19 UTC by stmazoni

## Description
Current implementation has problem, it doesn't show sample list well, I tested on Pixel 6 with Android 13.

I removed changing external_files_dir path. It changed directory path from '/storage/emulated/0/Android/data/com.khronos.vulkan_samples/files' to '/storage/emulated/0/com.khronos.vulkan_samples/'. But on the build.md file guide to copy resource to '/storage/emulated/0/Android/data/com.khronos.vulkan_samples/files'. And also it is better to use '/storage/emulated/0/Android/data/com.khronos.vulkan_samples', because it is deleted automatically when application is deleted.

And about the permission, current logic makes not showing sample list on the Android 13 device. it is happen because WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE has no effect after API level 33, current logic think application doesn't have permissions. However it can be used without permission request after API level 19. https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE https://developer.android.com/reference/android/Manifest.permission#WRITE_EXTERNAL_STORAGE I add if API level is same or higher than 19(Kitkat), skip the checkPermissions() and assume it already have these permissions. It is also related with not working on S23 device on https://github.com/KhronosGroup/Vulkan-Samples/issues/646.

Fixes #646 

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)

2023-04-25 05:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-Samples?pullRequest=678) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-Samples?pullRequest=678) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-Samples?pullRequest=678) it.</sub>

2023-04-26 13:48 UTC, r-potter commented
@r-kaczynski will check for Samsung devices.

2023-04-26 14:27 UTC, r-kaczynski commented
<del>Tested this branch on S23+ and S22 and after granting permissions I get this screen:
![image](https://user-images.githubusercontent.com/124259278/234606428-29dcd904-6045-4077-9163-3858bd6a5110.png)
Pressing the "Grant Permissions" button does nothing. I ran into a similar issue when trying to change the java code.</del>

Same as @SaschaWillems. I checked again and pushing the assets solves the problem.

2023-04-26 15:37 UTC, SaschaWillems requested changes
Doesn't work on my Pixel 4a either (latest firmware, Android 13). I do get a file permission dialog, but granting the permission doesn't return to the samples. If I manually go back, all samples simply crash at startup.

Log cat tells me it can't open the file:

Error Message: Failed to open file: /storage/emulated/0/Android/data/com.khronos.vulkan_samples/files/assets/fonts/Roboto-Regular.ttf

2023-04-26 22:45 UTC, stmazoni commented
> Just checked again, and it seems that the build step simply didn't push the assets. After manually pushing them, and setting the permissions the samples work fine.

It is not related with this PR.
I also cannot push assets, even adb push assets folder is not working. I pushed with using Windows file explorer. It seems because of security, and happen when pushed folder has another folders internally. I am checking it is security  policy or not in internally.

2023-06-05 09:38 UTC, JoseEmilio-ARM commented
> ~Tested this branch on S23+ and S22 and after granting permissions I get this screen: ![image](https://user-images.githubusercontent.com/124259278/234606428-29dcd904-6045-4077-9163-3858bd6a5110.png) Pressing the "Grant Permissions" button does nothing. I ran into a similar issue when trying to change the java code.~
> 
> Same as @SaschaWillems. I checked again and pushing the assets solves the problem.

I've also noticed that when installing the samples on a new device, this screen might also appear if not granting notifications permissions (i.e. we do not have `<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>` in the [manifest](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/app/android/AndroidManifest.xml)) which makes the error message about assets misleading. Manually granting notifications permissions fixed the issue for me.

2023-07-03 15:30 UTC, JoseEmilio-ARM commented
Hi @stmazoni  , since #713 has now been merged, can we close this PR now?

2023-07-12 01:51 UTC, closed without merging