Pack assets into APK to fix Android 11 permission issues
KhronosGroup/Vulkan-Samples pull request #692
Opened 2023-05-05 15:21 UTC by r-kaczynski

## Description

Vulkan Samples stores all it's assets and output files outside the app's directory. Android 11's permission update made this strategy no longer work.
My solution to this is to pack the assets with the APK and change where output files are located.
I've tested almost all API and performance samples on Windows, Android and Linux. I was not able to test the multi_draw_indirect sample on Linux as my device was not capable of running it.
The impact on build times is negligible (around 1% increase) and the APK's size goes up to 600MB and 550MB for debug and release respectively.
This PR is a proposal to change how assets are loaded on Android. This PR overlaps with https://github.com/KhronosGroup/Vulkan-Samples/pull/678, and we are happy for the team to take whichever solution you prefer
Fixes #646

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules

2023-05-05 15:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-Samples?pullRequest=692) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-Samples?pullRequest=692) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-Samples?pullRequest=692) it.</sub>

2023-05-05 17:16 UTC, gpx1000 commented
What do we think about using asset packs?

https://developer.android.com/guide/playcore/asset-delivery

2023-05-05 17:22 UTC, tomadamatkinson commented
Not opposed to asset packs. Have you had experience with them in the past?

2023-05-05 18:07 UTC, gpx1000 commented
Yep, I've used them; pretty happy with the results of using them.  I think they might even make sense to use in a template showing how to setup a vulkan project.  More on that later ;-)

2023-05-05 18:37 UTC, tomadamatkinson reviewed
I will have another read over this later and leave some review comments. I think the approach in this PR is a nice stop gap.

I'm open to learning more about asset packs. We might want to support both routes as I imagine there are some best practices we can show with both approaches

2023-05-22 17:56 UTC, SaschaWillems requested changes
Sadly doesn't work for me on Windows. The APK doesn't contain any assets. In your PR you changed the .sh file for generating the android gradle build files, but I don't see any change to the windows .bat file. I guess that's simply missing and needs to be fixed.

2023-05-31 19:56 UTC, SaschaWillems commented
Still doesn't work for me, even with the latest changes. My APK is only 180 MBytes and doesn't contain any assets. Any idea as to why this happens (on Windows)?

2023-06-02 23:36 UTC, w-pearson commented
I believe the issue is that you need to run the `generate_android_gradle.sh` script from within `build/android_gradle`, so that the `../../assets` path works. Doing so generated a full-sized APK for me, while running the script in the root directory did not (it gave a <code>-- Asset dir not exists at \`C:/Users/w.pearson/source/repos/Vulkan-Samples/../../assets\`</code> message but still generated the gradle files). This is on Windows but using Git Bash to run the shell script.

Unfortunately that APK still seemed to be unable to actually load the assets still, crashing when I actually selected a sample:

```
06-02 16:21:03.742  3364  3464 E VulkanSamples: [error] [samples/api/hello_triangle/hello_triangle.cpp:681] Failed to compile shader, Error: ERROR: #version: ES shaders for SPIR-V require version 310 or higher
06-02 16:21:03.742  3364  3464 E VulkanSamples: ERROR: 1 compilation errors.  No code generated.
06-02 16:21:03.742  3364  3464 E VulkanSamples: 
06-02 16:21:03.742  3364  3464 E VulkanSamples: 
06-02 16:21:03.742  3364  3464 E VulkanSamples: 
06-02 16:21:03.742  3364  3464 E VulkanSamples: [error] [framework/platform/android/asset_manager.cpp:52] Failed to open file: shaders/triangle.frag
06-02 16:21:03.742  3364  3464 E VulkanSamples: [error] [framework/platform/android/asset_manager.cpp:67] Tried to read size of a null asset
06-02 16:21:03.742  3364  3464 E VulkanSamples: [error] [samples/api/hello_triangle/hello_triangle.cpp:681] Failed to compile shader, Error: ERROR: #version: ES shaders for SPIR-V require version 310 or higher
06-02 16:21:03.742  3364  3464 E VulkanSamples: ERROR: 1 compilation errors.  No code generated.
06-02 16:21:03.742  3364  3464 E VulkanSamples: 
06-02 16:21:03.742  3364  3464 E VulkanSamples: 
06-02 16:21:03.742  3364  3464 E VulkanSamples: 
```

2023-06-04 02:50 UTC, kamaroyl commented
Cheers, confirmed this works building from Windows and deployed to a Pixel 6 Pro running Android 13

2023-06-04 03:19 UTC, kamaroyl commented
It does look like adding `PendingIntent.FLAG_MUTABLE` causes a crash for some of the extensions:
* descriptor buffer
* fragment_shader_barycentric
* Fragment shading rate
* Dynamic fragment shading rate
* VK_EXT_graphics_pipeline_library
* Logic operations dynamic sate
* Memory budget
* Mesh Shader Culling
* Mesh shader sample
* Arm OpenCL Interoperability
* VK_KHR_portability_subset
* Push descriptors
* Ray queries
* Ray tracing reflection
* Ray tracing basic
* Ray tracing extended
* Vertex Dynamic State

Exception is:
```
FATAL EXCEPTION: Thread-2
                                                                                                    Process: com.khronos.vulkan_samples, PID: 21795
                                                                                                    java.lang.IllegalArgumentException: com.khronos.vulkan_samples: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
                                                                                                    	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
                                                                                                    	at android.app.PendingIntent.getActivity(PendingIntent.java:470)
                                                                                                    	at android.app.PendingIntent.getActivity(PendingIntent.java:434)
                                                                                                    	at com.khronos.vulkan_samples.NativeSampleActivity.fatalError(NativeSampleActivity.java:81)
```

2023-07-03 15:29 UTC, JoseEmilio-ARM commented
Hi @r-kaczynski , since #713 has now been merged, can we close this PR now?

2023-08-03 15:55 UTC, SaschaWillems commented
@marty-johnson59: With #713 merged I think it's fine to close this.

2023-08-03 15:59 UTC, marty-johnson59 commented
OK, closing.  LMK if https://github.com/KhronosGroup/Vulkan-Samples/pull/713 doesn't cover the need and we can reopen..

2023-08-03 15:59 UTC, closed without merging