Framework improvements 5: Implemented GPU class
KhronosGroup/Vulkan-Samples pull request #70
Opened 2020-02-21 14:43 UTC by JoseEmilio-ARM

This introduces a PhysicalDevice, which is currently a refactor/wrapper for the VkPhysicalDevice. This will be the basis for the extension changes in upcoming performance samples that use device extensions. The distinction is the PhysicalDevice understands its properties and features and can request extension feature structures in a simple way. In addition to this it should also composite these extension feature structures so when you pass the PhysicalDevice to the Device, it can retrieve them all. This is because extension structures need to be daisy chained in a linked list, and the Device shouldn't need to understand how to do this.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes build and run on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)

2020-02-24 10:18 UTC, gary-sweet requested changes
framework/platform/unix/direct_window.cpp: In member function 'virtual VkSurfaceKHR_T* vkb::DirectWindow::create_surface(vkb::Instance&)':
framework/platform/unix/direct_window.cpp:234:27: error: 'class vkb::Instance' has no member named 'get_gpu'; did you mean 'query_gpus'?
  auto phys_dev = instance.get_gpu();
                           ^~~~~~~

2020-02-24 11:13 UTC, JoseEmilio-ARM commented
> framework/platform/unix/direct_window.cpp: In member function 'virtual VkSurfaceKHR_T* vkb::DirectWindow::create_surface(vkb::Instance&)':
> framework/platform/unix/direct_window.cpp:234:27: error: 'class vkb::Instance' has no member named 'get_gpu'; did you mean 'query_gpus'?
> auto phys_dev = instance.get_gpu();
> ^~~~~~~

no, I think we are just missing a `.get_handle()` there, will push the fix now

2020-02-25 09:04 UTC, gary-sweet submitted a review, later dismissed

2020-03-04 17:32 UTC, mattruschnv submitted a review, later dismissed

2020-03-17 14:15 UTC, aurolou submitted a review, later dismissed

2020-03-20 08:04 UTC, aurolou approved these changes

2020-03-20 11:27 UTC, gary-sweet approved these changes

2020-03-20 14:23 UTC, merged