Add Tracy Profiler Support
KhronosGroup/Vulkan-Samples pull request #757
Opened 2023-07-17 18:16 UTC by tomadamatkinson

## Description

Adds Tracy Profiler support. This will allow samples to show the stats and usage that they want to show to users without needing to clutter the Sample GUI

This can be extended in the future to instrument up core parts of the framework and samples that we want to draw the users attention too. It can also be used to show how multi-threading can be used with Vulkan

For now I have hooked this into our stats system so that we can show more stat information to users without worrying about cluttering the main GUI. We can still use the main sample GUI to show stats aswell!! I also added support for VMA Memory Budgets to show heap usage

We can use this to track other useful information such as the amount of vertices we expect to render for a given frame or the amount of geometry in the scene graph

Tracy also has Vulkan support however I have not played around with this yet

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/6977035/375cf16a-d262-4418-a8e0-563635593fc5)

String names for VkMemoryTypeFlags are taking from vulkan.hpp instead of adding to the existing vkb::to_string() set

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
  
## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](./../samples/extensions/conditional_rendering)

2023-07-19 15:36 UTC, asuessenbach reviewed
Is the concurrency stuff in the *.yml files related to adding tracy?

Besides that, I'm not familiar with tracy. How would I get that nice little tracy window?

2023-07-19 15:36 UTC, asuessenbach commented on framework/stats/stats.cpp
> +		average /= c.second.size();
Maybe: `float average = std::accumulate( c.second.begin(), c.second.end(), 0.0f ) / c.second.size();`

2023-07-20 07:51 UTC, tomadamatkinson commented
> Is the concurrency stuff in the *.yml files related to adding tracy?
> 
> 
> 
> Besides that, I'm not familiar with tracy. How would I get that nice little tracy window?

The concurrency stuff isn't related, I can make a small PR for these changes if needed. Just threw it in here as I had lots of jobs running and not automatically cancelling outdated ones.

To use Tracy you should be able to run './scripts/tracy.py' and it will build and run the window. I have only tested this on Linux and you do need to install system libraries.

I can give it a go on windows at some point this week and make sure it works. It is likely that it won't work first time

2023-07-24 14:07 UTC, asuessenbach commented
> It is likely that it won't work first time

And you're right, tracy on windows is not supported.

> The concurrency stuff isn't related,

You can keep it in, if you like. I just wanted to make that I didn't miss something here.

2023-07-24 14:41 UTC, SaschaWillems commented
> > It is likely that it won't work first time
> 
> And you're right, tracy on windows is not supported.
> 

I'm pretty sure tracy works on Windows. I'm using it in one of my projects and I mainly develop on windows ;)

2023-07-24 14:47 UTC, tomadamatkinson commented
Tracy is supported. It is likely my script doesn't work on windows - Yet!

The script was meant as a build helper as you need the same Tracy version as TracyClient version used in the app.

I've only had chance to get this helper working on Linux but i should have some free time tonight to test it out on windows.

The latest Tracy download from GitHub should also work (again not tested this as I was focused on the script)

2023-07-25 09:51 UTC, gary-sweet commented
The build script for Tracy doesn't work for me in Linux sadly:

```
../../../server/TracySourceView.cpp: In member function ‘bool tracy::SourceView::Disassemble(uint64_t, const tracy::Worker&)’:
../../../server/TracySourceView.cpp:736:46: error: ‘CS_GRP_BRANCH_RELATIVE’ was not declared in this scope
  736 |                 else if( detail.groups[j] == CS_GRP_BRANCH_RELATIVE && opType < OpType::Branch ) opType = OpType::Branch;
      |                                              ^~~~~~~~~~~~~~~~~~~~~~
../../../server/TracySourceView.cpp:739:46: error: ‘CS_GRP_PRIVILEGE’ was not declared in this scope
  739 |                 else if( detail.groups[j] == CS_GRP_PRIVILEGE && opType < OpType::Privileged )
      |                                              ^~~~~~~~~~~~~~~~
```

2023-07-25 12:43 UTC, asuessenbach commented
> The latest Tracy download from GitHub should also work (again not tested this as I was focused on the script)

Not exactly. I get this error:
![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/17293593/3f0a2b33-0228-4378-9ca0-160e95e08fbc)

2023-07-25 20:28 UTC, tomadamatkinson commented
@asuessenbach sorry for the delay on this. Each time I have thought I would have time I've had a distraction

I'm going to pin the submodule version to v9.1.0 https://github.com/wolfpld/tracy/tree/v0.9.1

This would make the versions compatible. I think I am currently on v.9.2.0 (using main)

Will also try the Windows build now with the script

@gary-sweet what is the version of your capstone library? I believe that build issue is coming from a missing dependency. The first printout at the top of the script is some install dependencies. It may work after building those

2023-07-25 21:08 UTC, tomadamatkinson commented
Wow, the Windows build is much more involved. Pinning the Tracy version to v0.9.1 makes our client compatible with the profiler

Added some download instructions to the script 

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/6977035/2ea1fcfc-15bd-4520-95c1-41b0b16caf59)

I would download automatically but as the release page packages Tracy in a 7zip archive I feel like it is best to let the user do this

After rebuilding samples I get this

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/6977035/b50942b4-a213-4e7c-9d47-ae93739e58c0)

2023-07-25 21:09 UTC, tomadamatkinson commented on framework/stats/stats.cpp
> +		average /= c.second.size();
Nice, yeah a bit more concise

2023-07-25 21:22 UTC, tomadamatkinson commented
Moved concurrency changes to another PR

2023-07-26 07:25 UTC, gary-sweet commented
> @gary-sweet what is the version of your capstone library? I believe that build issue is coming from a missing dependency. The first printout at the top of the script is some install dependencies. It may work after building those

```
libcapstone-dev:
  Installed: 4.0.1+really+3.0.5-1build1
```
 I literally just used the "sudo apt install libglfw3-dev libcapstone-dev libdbus-glib-1-dev libfreetype-dev" instruction from the script.

2023-07-26 07:30 UTC, gary-sweet commented
It's a bit weird though. The capstone change log would indicate that CS_GRP_BRANCH_RELATIVE was introduced in version 4.0. Grepping for that in /usr/include/capstone (which is where the build is looking) yields nothing however, despite Ubuntu claiming to have version 4.0.1.

2023-07-26 08:34 UTC, tomadamatkinson commented
Locally I have

```
libcapstone-dev/jammy,jammy,now 4.0.2-5 amd64 [installed]
libcapstone4/jammy,jammy,now 4.0.2-5 amd64 [installed,automatic]
```

Interesting how your lib says `4.0.1+really+3.0.5-1build1` as in its 4.0.1 but actually 3.0.5? What OS are you using?

2023-07-26 08:35 UTC, gary-sweet commented
> Interesting how your lib says `4.0.1+really+3.0.5-1build1` as in its 4.0.1 but actually 3.0.5? What OS are you using?

It's Ubuntu 20.04

2023-07-26 08:53 UTC, tomadamatkinson commented
Looking at making an Ubuntu docker build to export a usable executable. Here are the system dependencies for each platform as stated in the Tracy docs. I think the latest version of Tracy has revisions to the build system to make this work better but in general the build process is very much system specific.

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/6977035/5e5d802f-e8b4-4339-85a9-e66605218bf8)

Will post an update later

2023-07-26 10:27 UTC, asuessenbach reviewed
Works nice now with Tracy 0.9.1 on Win10!

2023-07-26 10:27 UTC, asuessenbach commented on framework/stats/stats.cpp
> +		for (size_t heap = 0; heap < memory_properties.memoryHeapCount; heap++)
Why don't you just use the flags from the memoryHeaps?

2023-07-26 10:27 UTC, asuessenbach commented on framework/stats/stats.cpp
> +			std::stringstream ss;
You don't have to use a `std::stringstream`:
`labels.push_back("Heap " + std::to_string(heap) + " " + vk::to_string(vk::MemoryPropertyFlags{flags}));
`

2023-07-27 17:34 UTC, SaschaWillems commented
Support for tracy would be great addition 👍 

But on windows you'll get a firewall notification when running the samples (at least for the first time), which may irritate users.

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/10283127/7a83f65b-19c4-4fdd-9c4b-1eff9dde9cc3)

So I'm not sure if we should always enable it by default, or if it's better to hide it behind a build time or runtime flag.

2023-07-27 17:55 UTC, SaschaWillems commented
> I would download automatically but as the release page packages Tracy in a 7zip archive I feel like it is best to let the user do this

Can we do that in the python script? There should be 7z libraries for python, so maybe we can make use of them to unpack the Windows version.

2023-07-27 18:59 UTC, tomadamatkinson commented
I'd be happy to add that if you believe it would make the process easier! It's a little frustrating that Tracy doesn't have a cmake build for their profiler

Happy to hide this behind a VKB_ENABLE_TRACY=ON flag

2023-08-03 16:22 UTC, SaschaWillems requested changes
Thanks for adding the flag. Works fine for me on Windows. 

But the android build fails for me with hundreds of errors from VMA:
```
V:/Vulkan-KHR-Samples/Vulkan-Samples/third_party/vma/include/vk_mem_alloc.h:2767:12: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
  static void* vma_aligned_alloc(size_t alignment, size_t size)
             ^
  V:/Vulkan-KHR-Samples/Vulkan-Samples/third_party/vma/include/vk_mem_alloc.h:2767:12: note: insert '_Nullable' if the pointer may be null
  static void* vma_aligned_alloc(size_t alignment, size_t size)
             ^
               _Nullable
  V:/Vulkan-KHR-Samples/Vulkan-Samples/third_party/vma/include/vk_mem_alloc.h:2767:12: note: insert '_Nonnull' if the pointer should never be null
  static void* vma_aligned_alloc(size_t alignment, size_t size)
             ^
               _Nonnull
```

Btw. I think we also need to adjust our documentation so people know that we have tracy support.

2023-08-03 16:52 UTC, SaschaWillems commented
Last time I checked on Windows this worked fine with Tracy 0.9.1, but if I try to connect now I get an error a protocol mismatch error? Did anything change recently?

2023-08-14 14:19 UTC, asuessenbach approved these changes, later dismissed

2023-08-22 09:17 UTC, asuessenbach reviewed
It compiles fine, both with and without VKB_ENABLE_TRACY defined.
But I get the same protocol mismatch error as Sascha got three weeks ago.

2023-08-22 09:17 UTC, asuessenbach commented on components/core/include/core/util/profiling.hpp
> +};
With `TRACY_ENABLE` defined, `get_instance` and `plots` are private, otherwise they are public?

2023-08-22 09:56 UTC, asuessenbach commented on framework/stats/stats.cpp
> +#include <vulkan/vulkan.hpp>
What warnings from vulkan.hpp do you want to hide here?

2024-03-11 21:26 UTC, tomadamatkinson commented
Picked this branch back up as the Tracy support does work. This branch got stalled on that fact that Tracy is hard to build for different platforms - this is a known limitation of the project.

I have created [this pr](https://github.com/wolfpld/tracy/pull/707) in an attempt to help improve Tracy in this area. Unfortunately you will not be able to use this branch to build Tracy due to the strict protocol constraints. If you would like to test this PR you will need to install Tracy from the release page or by following the Tracy.pdf guide.

If you are using version of ubuntu that does not include capstone 4+ you will need to manually build and install capstone 4+ in your distro for Tracy to build.

`VKB_PROFILING` was added to make Tracy's usage opt in. By default this option is OFF

For now I have only instrumented up the GLTF Loader. We do not need to instrument all functions with Tracy. It is useful to track the performance of high level systems such as scene iterations or multi threaded scenarios.

I have tested on Ubuntu 23.04, Windows 11 and Android. Tracy is disabled for Android for now as there are some networking considerations

(I will be addressing any CI issues over the next few days, There are likely going to be some nuances between actual machines and github runners)

2024-03-11 22:26 UTC, gpx1000 approved these changes, later dismissed

2024-03-12 13:33 UTC, asuessenbach commented
Unfortunately, I get an "Incompatible protocol" error, again:
![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/17293593/14dec197-6bd9-4c35-90de-dd3cceb8205c)

I just downloaded the release v0.10 from https://github.com/wolfpld/tracy/tags, started the Tracy.exe and got this.

2024-03-12 14:06 UTC, asuessenbach commented on framework/common/error.h
> +#include "core/util/error.hpp"
Why do you separate error.hpp for the other headers?

2024-03-12 14:06 UTC, asuessenbach commented on framework/gltf_loader.cpp
> +#include <core/util/profiling.hpp>
Why do you separate profiling.hpp from the other headers below?

2024-03-12 18:20 UTC, tomadamatkinson commented
Hey @asuessenbach, this branch is pinned to v0.10 can you confirm that you updated your submodules before building?

Before this branch was v0.9.1 so it may be that you still have that version checked out

2024-03-13 20:31 UTC, SaschaWillems commented
Works fine for me 👍🏻. Will try to do a proper review this weekend.

2024-03-18 09:44 UTC, asuessenbach commented
@tomadamatkinson You're right, I somehow missed to get the check out the right version. Works now!

2024-06-01 16:02 UTC, SaschaWillems submitted a review, later dismissed

2024-06-17 15:09 UTC, SaschaWillems commented
@tomadamatkinson: Could you fix the the merge conflicts? Would' love to see this merged, so we can add additional functionality based on your work. If you can't find the time, I'll happily try to help :)

2024-06-19 18:44 UTC, tomadamatkinson commented
@SaschaWillems ill take a look!

2024-06-24 16:04 UTC, tomadamatkinson commented
![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/6977035/1730ddcf-f8db-43ae-b539-533df859e3bd)

Rebased and tested on linux. To work with android devices i believe we need to port forward with adb and also give the application local network permissions. I have not tested this in this PR. On desktop this should work fine out of the box.

Works with Tracy version 0.10. When Tracy has a new official release with the CMake build system i helped with we can bump the submodule and point to that allowing users to seamlessly build the profiler.

I cannot test on Windows or Mac today but may be able too in the near future

@SaschaWillems let me know if there are any tweaks you want adding to this

2024-07-02 15:23 UTC, SaschaWillems approved these changes
Thank you very much. Worked out of the box for me on Windows with the Tracy 0.10 binary release 👍🏻

2024-07-29 01:39 UTC, gpx1000 approved these changes
Awesome, works here.

2024-07-30 08:36 UTC, gary-sweet approved these changes
Doesn't break anything for me

2024-08-09 14:37 UTC, marty-johnson59 commented
Merging - 3 approvals

2024-08-09 14:37 UTC, merged