Introduce helper functions vkb::[common::]select_surface_format
KhronosGroup/Vulkan-Samples pull request #761
Opened 2023-07-25 16:42 UTC by asuessenbach

## Description

It turned out, the surface format selection boilerplate was just used three times over all the samples. And the framework does it slightly differently.
But here are the helper functions to select a surface format (both for Vulkan and Vulkan-Hpp) and their usage in the samples.

Compiled and tested on Win10, using NVIDIA GPU.

Fixes #647

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
  
## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [x] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)
- [x] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](./../samples/extensions/conditional_rendering)

2023-07-28 18:22 UTC, SaschaWillems requested changes

2023-07-28 18:22 UTC, SaschaWillems commented on samples/api/hello_triangle/hello_triangle.cpp
> +	VkSurfaceFormatKHR format = vkb::select_surface_format(context.gpu, context.surface);
Note sure if we should remove this part. The hello_triangle samples should is intended to be as explicit as possible, so it's probably better to put the whole code from `vkb::select_surface_format` in here.

2023-07-28 18:22 UTC, SaschaWillems commented on samples/api/hpp_hello_triangle/hpp_hello_triangle.cpp
> +	vk::SurfaceFormatKHR surface_format = vkb::common::select_surface_format(gpu, surface);
Same as for the non-hpp hello_triangle sample.

2023-07-31 16:45 UTC, SaschaWillems commented on samples/api/hello_triangle/hello_triangle.cpp
> +	VkSurfaceFormatKHR format = vkb::select_surface_format(context.gpu, context.surface);
As per today's call it's fine if the function is used here.

2023-07-31 16:45 UTC, SaschaWillems commented on samples/api/hpp_hello_triangle/hpp_hello_triangle.cpp
> +	vk::SurfaceFormatKHR surface_format = vkb::common::select_surface_format(gpu, surface);
As per today's call it's fine if the function is used here.

2023-08-08 22:32 UTC, tomadamatkinson approved these changes

2023-08-14 15:14 UTC, gpx1000 approved these changes

2023-08-14 15:15 UTC, SaschaWillems approved these changes

2023-08-14 15:15 UTC, merged