CLI and Validation Fixes
KhronosGroup/Vulkan-Samples pull request #768
Opened 2023-08-01 21:49 UTC by tomadamatkinson

## Description

Fixes the Windows CLI issues. Now attempts to attach to the parent process console before allocating a new one. This stops a second terminal from being used in place of an already usable terminal

Fixes some of the validation layer logic which stopped some samples from working on Windows

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [x] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
  
## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](./../samples/extensions/conditional_rendering)

2023-08-01 22:26 UTC, gpx1000 approved these changes

2023-08-02 12:03 UTC, asuessenbach reviewed
I think, the validation layer issue should be handled in a separate PR.
Besides that, it looks good to me.

2023-08-02 18:50 UTC, SaschaWillems requested changes
As already noted by @asuessenbach, the validation changes should be moved out of this PR. We are currently talking about how to fix this in a different way.

2023-08-08 22:23 UTC, tomadamatkinson commented
@SaschaWillems @asuessenbach please see #773 and #774

2023-08-08 22:23 UTC, closed without merging