Add a new sample - dynamic line rasterization
KhronosGroup/Vulkan-Samples pull request #790
Opened 2023-09-01 09:04 UTC by Krzysztof-Dmitruk-Mobica

## Description

This pull request proposes a sample that demonstrates methods for dynamically customizing the appearance of rendered lines.

### Notes
Tested on:

Ubuntu 23.04
Intel i7-11800H
Intel TigerLake-H GT1/Nvidia T600 Mobile
32 GB RAM

Please ensure the following points are checked:

- [X] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Code-Style)
- [X] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [X] I have commented any added functions (in line with Doxygen)
- [X] I have commented any code that could be hard to understand
- [X] My changes do not add any new compiler warnings
- [X] My changes do not add any new validation layer errors or warnings
- [X] I have used existing framework/helper functions where possible
- [X] My changes do not add any regressions
- [X] I have tested every sample to ensure everything runs correctly
- [X] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [X] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
  
## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [X] I have tested the sample on at least one compliant Vulkan implementation
- [X] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.md#General-Requirements)
- [X] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [X] Any dependent assets have been merged and published in downstream modules
- [X] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)
- [X] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](./../samples/extensions/conditional_rendering)

2023-09-04 18:04 UTC, SaschaWillems requested changes
Thank you very much for this great sample! Code and sample look fine to me and work as expected on my setup (Win11 + RTX 2060).

I only have a minor request: Can you add a screenshot of the sample to the readme?

2023-09-05 08:40 UTC, Krzysztof-Dmitruk-Mobica commented
Sure! I've added a screenshot.

2023-09-05 12:00 UTC, asuessenbach reviewed
Besides one minor issue (three times), it's a great example!

2023-09-05 12:00 UTC, asuessenbach commented on samples/extensions/dynamic_line_rasterization/dynamic_line_rasterization.cpp
> +	                                                    VMA_MEMORY_USAGE_GPU_TO_CPU);
You probably mean `VMA_MEMORY_USAGE_CPU_TO_GPU` ?

2023-09-05 12:00 UTC, asuessenbach commented on samples/extensions/dynamic_line_rasterization/dynamic_line_rasterization.cpp
> +	                                                        VMA_MEMORY_USAGE_GPU_TO_CPU);
As above.

2023-09-05 12:00 UTC, asuessenbach commented on samples/extensions/dynamic_line_rasterization/dynamic_line_rasterization.cpp
> +	                                                         VMA_MEMORY_USAGE_GPU_TO_CPU);
As above

2023-09-05 12:44 UTC, Krzysztof-Dmitruk-Mobica commented on samples/extensions/dynamic_line_rasterization/dynamic_line_rasterization.cpp
> +	                                                    VMA_MEMORY_USAGE_GPU_TO_CPU);
Fixed, thank you for noticing that.

2023-09-05 12:57 UTC, asuessenbach approved these changes

2023-09-07 08:02 UTC, gary-sweet commented
Unfortunately I can't test this. My hardware doesn't support stippled lines or dynamic polygon mode.

It would be great if the sample could check the support for each feature and just not use any that weren't supported rather than requiring everything in order to run anything.

2023-09-10 11:42 UTC, SaschaWillems approved these changes

2023-09-11 15:07 UTC, merged