Add sample files and updated documentation
KhronosGroup/Vulkan-Samples pull request #849
Opened 2023-11-16 00:22 UTC by RodrigoHolztrattner-QuIC

## Description

![image](https://github.com/KhronosGroup/Vulkan-Samples/assets/104386913/e994eb51-0567-4a12-accc-2d4f5297abba)

Adds the Mobile NeRF sample, which is a modified version of the WebGL version developed by Google (https://mobile-nerf.github.io).

This version runs much faster on Vulkan and is a very good demonstration of a new rendering technique that is based on neural radiance fields.

Fixes #<issue number>

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#General-Requirements)

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](./../samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](./../antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

2023-11-16 00:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/Vulkan-Samples?pullRequest=849) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/Vulkan-Samples?pullRequest=849) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/Vulkan-Samples?pullRequest=849) it.</sub>

2023-11-19 14:39 UTC, SaschaWillems commented
There is no need to include `stb_image.h`. It's already included in our repo via the stb submodule in https://github.com/KhronosGroup/Vulkan-Samples/tree/main/third_party

2023-11-19 14:56 UTC, SaschaWillems commented
And any reason this is in the `extensions` folder? And why is it called `mobile_nerf` when it's running fine on desktop?

Maybe we need a new category for samples like these that showcase specific functionality not directly related to Vulkan?

2023-11-19 15:00 UTC, SaschaWillems commented
Gave it a first test on Windows 11 + Nvidia RTX 4070 and the sample works, but there are some oddities:

- I can't rotate the camera, only zoom in and out
- The sample doesn't properly handle resize. If I e.g. make the window larger, the viewport isn't adjusted.

2023-11-20 15:43 UTC, RodrigoHolztrattner-QuIC commented
@SaschaWillems just addressing some of your questions:
- Thanks for pointing out, I will update the branch to use the repo stb instead
- Yeah, makes sense to just call it NeRF or NeRF Rendering since it (should) generally works well on any device that supports Vulkan
- For the camera/viewport issue, I will also be fixing these on the next couple days, the initial iteration had a static rotating camera around the loaded object, but a free camera will probably work much better

2023-11-21 09:56 UTC, gary-sweet commented on samples/extensions/mobile_nerf/mobile_nerf.cpp
> +	add_device_extension(VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME);
Does this sample actually use any descriptor indexing features?

I ask this because I've tried it on one of our drivers that doesn't support descriptor indexing (with this line commented out) and it appears to work. If it's not actually required, we probably shouldn't be requesting it.

2023-11-23 17:55 UTC, JoseEmilio-ARM requested changes
Thanks a lot for this sample! I have a couple of questions:
1. Could we use the `std_image.h` included in the top level `third_party/stb`?
2. Ran it on an Android phone but the camera direction does not change in response to touch, is that expected?

2023-11-29 23:33 UTC, RodrigoHolztrattner-QuIC commented on samples/extensions/mobile_nerf/mobile_nerf.cpp
> +	add_device_extension(VK_EXT_DESCRIPTOR_INDEXING_EXTENSION_NAME);
Thanks for pointing out, descriptor indexing extension removed!

2023-11-29 23:36 UTC, RodrigoHolztrattner-QuIC commented
@SaschaWillems and @JoseEmilio-ARM 
- Sample renamed to just NeRF (including supporting files)
- Created the "general" category and moved the sample there 
- You should be able to rotate the camera now
- Resizing code added, it should work as expected on windows

Thanks for reviewing!

2023-12-04 16:00 UTC, josmil1 commented
Unfortunately the latest version is crashing for me on Android. I tried a couple of devices (Pixel 6, Vivo X90):
```
E/VulkanSamples: [error] [samples/general/nerf/nerf.cpp:1247] Failed to open mlp data
I/VulkanSamples: [info] Parsing mlp data /storage/emulated/0/Android/data/com.khronos.vulkan_samples/files/assets/scenes/morpheus_team/lego_ball_phone/mlp.json
E/VulkanSamples: [error] [framework/platform/platform.cpp:169] Error Message: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
E/VulkanSamples: [error] [framework/platform/platform.cpp:170] Failed when running application nerf
````

2023-12-04 16:01 UTC, JoseEmilio-ARM commented
Unfortunately the latest version is crashing for me on Android. I tried a couple of devices (Pixel 6, Vivo X90):
```
E/VulkanSamples: [error] [samples/general/nerf/nerf.cpp:1247] Failed to open mlp data
I/VulkanSamples: [info] Parsing mlp data /storage/emulated/0/Android/data/com.khronos.vulkan_samples/files/assets/scenes/morpheus_team/lego_ball_phone/mlp.json
E/VulkanSamples: [error] [framework/platform/platform.cpp:169] Error Message: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
E/VulkanSamples: [error] [framework/platform/platform.cpp:170] Failed when running application nerf
```

2023-12-04 16:42 UTC, JoseEmilio-ARM approved these changes
Tested again and had no issues with the sample (both Debug and Release builds), approving the PR

2023-12-05 06:10 UTC, SaschaWillems commented
Samples works fine for me on Win11 with an RTX 4070.

There are some minor nitpicks mostly not directly related to the samples, but I don't want to defer the release of it and they can be fixed afterwards. Will probably open an issue for those after the sample has been merged.

2023-12-05 06:10 UTC, SaschaWillems approved these changes

2023-12-06 12:00 UTC, cforfang commented
How is the main (NeRF) render-pass output synchronised with the UI rendering? I see the NeRF render-pass has an 1 -> external sub-pass dependency, but this is using dstStage = BOTTOM, so doesn't sync with the UI pass. Similarly, the UI pass (looking at the swapchain re-creation code) only appears to have an incoming dependency on COLOR -> COLOR, but COLOR happens after FRAGMENT where the NeRF output would presumably be read.

Good chance I'm missing something, so to ask :) Has anyone run with the GPU validation layer to check if there are any complains about sync issues?

2023-12-06 20:03 UTC, marty-johnson59 commented
Given we've resolved the issues we discussed on Monday, I'll go ahead and merge this.  @RodrigoHolztrattner-QuIC, please see if you can reply to @cforfang's comment above. Thanks!

I'll merge the assets too..

2023-12-06 20:03 UTC, merged

2023-12-06 20:19 UTC, RodrigoHolztrattner-QuIC commented
> How is the main (NeRF) render-pass output synchronised with the UI rendering? I see the NeRF render-pass has an 1 -> external sub-pass dependency, but this is using dstStage = BOTTOM, so doesn't sync with the UI pass. Similarly, the UI pass (looking at the swapchain re-creation code) only appears to have an incoming dependency on COLOR -> COLOR, but COLOR happens after FRAGMENT where the NeRF output would presumably be read.
> 
> Good chance I'm missing something, so to ask :) Has anyone run with the GPU validation layer to check if there are any complains about sync issues?

I could be wrong on this, but my view is that _dstStage = BOTTOM_ basically makes no assumption about the next dependency (as it's the same as _<dstStage = NONE, dstAccess = NONE>_) but the render pass we use to draw the UI waits for all previous commands, since it uses _srcStage = BOTTOM_ (which should be the same as _<srcStage = ALL_COMMANDS, srcAccess = NONE>_).

Here is where we setup the begin render pass for the UI: https://github.com/RodrigoHolztrattner-QuIC/Vulkan-Samples/blob/0bd1509453b28fffcdc37b9af13ca2bd77ddb1b4/samples/general/nerf/nerf.cpp#L762 
And here is where the UI dependencies are set: https://github.com/RodrigoHolztrattner-QuIC/Vulkan-Samples/blob/0bd1509453b28fffcdc37b9af13ca2bd77ddb1b4/framework/api_vulkan_sample.cpp#L758) 

I believe some other examples are doing something similar, where they have _dstStage = BOTTOM_ at their last dependency before the UI pass. I didn't see any synchronization validation error on the platforms I tested (tried debug builds with validation active), but please let me know in case someone sees any.

2023-12-07 06:18 UTC, SaschaWillems commented
The sample does indeed show a sync error, but it's related to the depth attachment:

```
[error] [framework\core\instance.cpp:50] 1544472022 - SYNC-HAZARD-WRITE-AFTER-WRITE: Validation Error: [ SYNC-HAZARD-WRITE-AFTER-WRITE ] Object 0: handle = 0x535b660000000043, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x5c0ec5d6 | vkCmdBeginRenderPass: Hazard WRITE_AFTER_WRITE in subpass 0 for attachment 1 image layout transition (old_layout: VK_IMAGE_LAYOUT_UNDEFINED, new_layout: VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL). Access info (usage: SYNC_IMAGE_LAYOUT_TRANSITION, prior_usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, write_barriers: 0, command: vkCmdEndRenderPass, seq_no: 6,renderpass: VkRenderPass 0x808562000000003f[], reset_no: 1).
```
No sync errors related to color attachments though.

2023-12-08 22:13 UTC, cforfang commented
> the render pass we use to draw the UI waits for all previous commands, since it uses _srcStage = BOTTOM_ (which should be the same as _<srcStage = ALL_COMMANDS, srcAccess = NONE>_)

Ah, thank you I missed there is probably a transitive dependency going through BOTTOM here! I'd be a bit concerned about the access-masks being generally None, as if these are not correct there is only an _execution_ dependency not a _memory_ dependency (meaning ordering would be correct, but the right caches might not be flushed/invalidated to make sure the data is written/read correctly) -- but if the GPU sync validation layer is happy, then I'm happy :)