Change vkb::HPPGLTFLoader from a facade over vkb::GLTFLoader to a self-contained class using Vulkan-Hpp.
KhronosGroup/Vulkan-Samples pull request #861
Opened 2023-12-11 13:43 UTC by asuessenbach

## Description

Includes
- slightly improved `struct [HPP]Meshlet` in `[hpp_]api_vulkan_sample.h`;
- additional facade-functions in `common/hpp_utils.h`;
- a new function `is_image_format_supported` in `HPPPhysicalDevice`, that catches the exception thrown on not supported formats;
- some minor corrections/improvements in `GLTFLoader` and `scene_graph::Scene`
- adjustments according to the new `scene_graph/component` classes in `HPPVulkanSample` and `rendering::subpasses::HPPForwardSubpass`;
- new facade classes `scene_graph::components::HPPCamera`, `scene_graph::components::HPPLight`, `scene_graph::components::HPPMesh`, `scene_graph::components::HPPPBRMaterial`, `scene_graph::components::HPPSampler`, `scene_graph::components::HPPTexture`, `scene_graph::components::HPPTransform`, `scene_graph::HPPNode`, `scene_graph::HPPScene`, and `scene_graph::scripts::HPPAnimation`
- adjustments in facade classes `scene_graph::components::HPPImage` and `scene_graph::components::HPPSubMesh`
- fully transcoded classes `scene_graph::components::HPPPerspectiveCamera` and `scene_graph::components::image::HPPAstc`
- a fix in `gshader_to_mshader.mesh`.

Build tested on Win10 with VS2022. All hpp-based samples tested on Win10 with NVidia GPU.

## General Checklist:

Please ensure the following points are checked:

- [x] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#Code-Style)
- [x] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#Copyright-Notice-and-License-Template)
- [x] I have commented any added functions (in line with Doxygen)
- [x] I have commented any code that could be hard to understand
- [x] My changes do not add any new compiler warnings
- [x] My changes do not add any new validation layer errors or warnings
- [x] I have used existing framework/helper functions where possible
- [x] My changes do not add any regressions
- [x] I have tested every sample to ensure everything runs correctly
- [x] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [x] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#General-Requirements)

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [x] I have tested the sample on at least one compliant Vulkan implementation
- [x] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.md#General-Requirements)
- [x] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [x] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](./../samples/README.md)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](./../samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](./../antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

2023-12-17 16:43 UTC, SaschaWillems commented
Can we discuss this in the next samples call? The PR itself is fine, but it has a lot of framework changes and I'm unsure how these align with the framework direction we recently talked about.

2023-12-17 22:45 UTC, asuessenbach commented
> Can we discuss this in the next samples call?

Sure, but I can't attend the next call. Will be back again next year.

2023-12-18 11:59 UTC, gary-sweet requested changes
I'm seeing a bunch of compilation errors with this change unfortunately.

```
In file included from Vulkan-Samples/framework/scene_graph/hpp_scene.h:25,
                 from Vulkan-Samples/framework/hpp_vulkan_sample.h:27,
                 from Vulkan-Samples/framework/hpp_api_vulkan_sample.h:20,
                 from Vulkan-Samples/framework/hpp_api_vulkan_sample.cpp:18:
Vulkan-Samples/framework/scene_graph/components/hpp_sampler.h: In constructor 'vkb::scene_graph::components::HPPSampler::HPPSampler(const string&, vkb::core::HPPSampler&&)':
Vulkan-Samples/framework/scene_graph/components/hpp_sampler.h:41:90: error: invalid cast of an rvalue expression of type 'std::remove_reference<vkb::core::HPPSampler&>::type' {aka 'vkb::core::HPPSampler'} to type 'vkb::core::Sampler&&'
      vkb::sg::Sampler(name, reinterpret_cast<vkb::core::Sampler &&>(std::move(vk_sampler)))
                                                                                          ^
In file included from Vulkan-Samples/framework/hpp_vulkan_sample.h:27,
                 from Vulkan-Samples/framework/hpp_api_vulkan_sample.h:20,
                 from Vulkan-Samples/framework/hpp_gltf_loader.cpp:22:
Vulkan-Samples/framework/scene_graph/hpp_scene.h: In instantiation of 'void vkb::scene_graph::HPPScene::add_component(std::unique_ptr<_Tp>&&) [with T = vkb::scene_graph::components::HPPCamera]':
Vulkan-Samples/framework/hpp_gltf_loader.cpp:461:47:   required from here
Vulkan-Samples/framework/scene_graph/hpp_scene.h:51:33: error: invalid cast of an rvalue expression of type 'std::remove_reference<std::unique_ptr<vkb::scene_graph::components::HPPCamera>&>::type' {aka 'std::unique_ptr<vkb::scene_graph::components::HPPCamera>'} to type 'std::unique_ptr<vkb::sg::Camera, std::default_delete<vkb::sg::Camera> >&&'
   vkb::sg::Scene::add_component(reinterpret_cast<std::unique_ptr<typename T::ComponentType> &&>(std::move(component)));
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Vulkan-Samples/framework/scene_graph/hpp_scene.h: In instantiation of 'void vkb::scene_graph::HPPScene::set_components(std::vector<std::unique_ptr<_Tp> >&&) [with T = vkb::scene_graph::components::HPPLight]':
Vulkan-Samples/framework/hpp_gltf_loader.cpp:713:50:   required from here
Vulkan-Samples/framework/scene_graph/hpp_scene.h:85:34: error: invalid cast of an rvalue expression of type 'std::remove_reference<std::vector<std::unique_ptr<vkb::scene_graph::components::HPPLight> >&>::type' {aka 'std::vector<std::unique_ptr<vkb::scene_graph::components::HPPLight> >'} to type 'std::vector<std::unique_ptr<vkb::sg::Light, std::default_delete<vkb::sg::Light> >, std::allocator<std::unique_ptr<vkb::sg::Light, std::default_delete<vkb::sg::Light> > > >&&'
   vkb::sg::Scene::set_components(reinterpret_cast<std::vector<std::unique_ptr<typename T::ComponentType>> &&>(std::move(components)));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Vulkan-Samples/framework/scene_graph/hpp_scene.h: In instantiation of 'void vkb::scene_graph::HPPScene::set_components(std::vector<std::unique_ptr<_Tp> >&&) [with T = vkb::scene_graph::components::HPPSampler]':
Vulkan-Samples/framework/hpp_gltf_loader.cpp:714:39:   required from here
Vulkan-Samples/framework/scene_graph/hpp_scene.h:85:34: error: invalid cast of an rvalue expression of type 'std::remove_reference<std::vector<std::unique_ptr<vkb::scene_graph::components::HPPSampler> >&>::type' {aka 'std::vector<std::unique_ptr<vkb::scene_graph::components::HPPSampler> >'} to type 'std::vector<std::unique_ptr<vkb::sg::Sampler, std::default_delete<vkb::sg::Sampler> >, std::allocator<std::unique_ptr<vkb::sg::Sampler, std::default_delete<vkb::sg::Sampler> > > >&&'

Vulkan-Samples/framework/scene_graph/hpp_scene.h:51:33: error: invalid cast of an rvalue expression of type 'std::remove_reference<std::unique_ptr<vkb::scene_graph::components::HPPSubMesh>&>::type' {aka 'std::unique_ptr<vkb::scene_graph::components::HPPSubMesh>'} to type 'std::unique_ptr<vkb::sg::SubMesh, std::default_delete<vkb::sg::SubMesh> >&&'
   vkb::sg::Scene::add_component(reinterpret_cast<std::unique_ptr<typename T::ComponentType> &&>(std::move(component)));
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

2024-01-09 18:05 UTC, asuessenbach commented
@gary-sweet What compiler are you using? Obviously, the compilers in our CI are less picky. Maybe we should add that compiler to our CI?
That said, would you please try again if my latest change resolves those errors?

2024-01-26 08:45 UTC, gary-sweet commented
> @gary-sweet What compiler are you using? Obviously, the compilers in our CI are less picky. Maybe we should add that compiler to our CI? That said, would you please try again if my latest change resolves those errors?

I'm not sure how but I completely missed your reply somehow. Apologies for that.
Sadly the latest changes haven't changed the compile errors.

The compiler is "gcc version 8.3.0 (stbgcc-8.3-1.0) " for aarch64

2024-01-30 06:11 UTC, SaschaWillems approved these changes
Compiles fine for me with MSVC 2022 17.8.4.

2024-05-07 07:59 UTC, asuessenbach commented
Closed for now, as the C/Cpp unification takes a different path.

2024-05-07 07:59 UTC, closed without merging