Add new sample for shader debugprintf
KhronosGroup/Vulkan-Samples pull request #945
Opened 2024-02-25 16:11 UTC by SaschaWillems

## Description

**Note:** This is a draft. The sample is (mostly) done, but documentation is still lacking.

This PR adds a new sample showing how to use debugprintf in shaders.

Fixes #926

## General Checklist:

Please ensure the following points are checked:

- [ ] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [ ] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [ ] I have commented any added functions (in line with Doxygen)
- [ ] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [ ] I have used existing framework/helper functions where possible
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

## Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out *in addition* to the General Checklist:
- [ ] I have tested the sample on at least one compliant Vulkan implementation
- [ ] If the sample is vendor-specific, I have [tagged it appropriately](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)
- [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
- [ ] Any dependent assets have been merged and published in downstream modules
- [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the [samples readme](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/samples/README.adoc)
- [ ] For new samples, I have added a tutorial README.md file to guide users through what they need to know to implement code using this feature. For example, see [conditional_rendering](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/conditional_rendering)
- [ ] For new samples, I have added a link to the [Antora navigation](https://github.com/KhronosGroup/Vulkan-Samples/blob/main/antora/modules/ROOT/nav.adoc) so that the sample will be listed at the Vulkan documentation site

2024-02-26 09:15 UTC, gary-sweet requested changes
We don't support debugPrintfEXT but I'm still seeing a couple of issues when I run this PR.

I get a validation error at the start:
`VUID-vkCreateInstance-ppEnabledExtensionNames-01388(ERROR / SPEC): msgNum: -437968512 - Validation Error: [ VUID-vkCreateInstance-ppEnabledExtensionNames-01388 ] | MessageID = 0xe5e52180 | vkCreateInstance(): pCreateInfo->ppEnabledExtensionNames[0] Missing extension required by the instance extension VK_KHR_display: VK_KHR_surface. The Vulkan spec states: All required extensions for each extension in the VkInstanceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCreateInstance-ppEnabledExtensionNames-01388)`

It terminates with an error about `VK_KHR_get_physical_device_properties2`:
```
[error] [framework/platform/platform.cpp:169] Error Message: Couldn't request feature from device as VK_KHR_get_physical_device_properties2 isn't enabled!
[error] [framework/platform/platform.cpp:170] Failed when running application shader_debugprintf
Segmentation fault
```
and then segfaults in `vkDestroySurfaceKHR()` called from `VulkanSample::~VulkanSample()`

2024-02-26 09:34 UTC, SaschaWillems commented
Thanks for noticing. The framework seems to add `VK_KHR_surface` explicitly and via glfw (which looks wrong on e.g. Windows as it shows up twice). I guess on your platform the implicit addition via glfw doesn't happen, hence it's missing. Will fix that.

2024-03-06 19:37 UTC, SaschaWillems commented
I have added a tutorial for this sample. It's now ready for review.

2024-03-07 15:12 UTC, asuessenbach reviewed
Great description on how to use it.

For some unknown reason, this sample "runs" incredibly slow on my machine (multiple seconds per frame). But when the Vulkan Configurator is running as well, I don't get any output anymore and the speed is as expected. Any idea on that?

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/README.adoc
> +It allows you to output invocation related debug messages from a give shader stage and can help to find problems or bugs together with a graphics debugger like a https://www.renderdoc.org[RenderDoc].
typo: give -> given
typo: like a -> like

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/README.adoc
> +Shader printf is a feature of the validation layers. So the firs step is to enable the `VK_LAYER_KHRONOS_validation` layer at instance creation. In addition to the layer(s) to be enabled we also need
typo: firs -> first

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/README.adoc
> +    validation_features.enabledValidationFeatureCount = 1;
instead of plain `1`, we should use `static_cast<uint32_t>(validation_feature_enables.size())`
Or with just one feature enabled, maybe just use a plain `VkValidationFeatureEnableEXT enable_printf = VK_VALIDATION_FEATURE_ENABLE_DEBUG_PRINTF_EXT;`

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/README.adoc
> +Shader printf messages are of `info` type, so in order for them to be passed to the callback you need to enable set the `VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT` `messageSeverity` flag.
typo: to enable set -> to enable

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/README.adoc
> +And then gather those so they can be displayed in the graphical user interface. The sample also checks if it's actually a printf message (`pMessageIdName == WARNING-DEBUG-PRINTF`), which is something
typo: one could you -> one could do

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/README.adoc
> +The default buffer size for debug outputs is limited. If you output a lot of messages, e.g. by doing a printf per fragment shader invocation, this may not suffice and you'll get a validation warning
Is there no way to increase that size programmatically?

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/README.adoc
> +This **does not** apply to outputting messages in graphics debuggers.
What is "This" here?
That the buffer size is limited? Or that you can increase it via VkConfig?

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/README.adoc
> +Using debug printf will consume a descriptor set, so if you use every last descriptor set it may not work and you may need to increase set count at pool allocation. Thus in the sample we allocate an
Maybe: you may need to increase set count -> you may need to increase the set count
Maybe/Typo: on the no. and/or size fo -> on the number and/or size of

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/shader_debugprintf.cpp
> +	validation_features.enabledValidationFeatureCount = 1;
maybe: `1` -> `static_cast<uint32_t>(validation_feature_enables.size())`

2024-03-07 15:12 UTC, asuessenbach commented on samples/extensions/shader_debugprintf/shader_debugprintf.cpp
> +	VkResult result = volkInitialize();
No need to `volkInitialize` here. It has already been called in `VulkanSample::prepare`.

2024-03-07 17:25 UTC, SaschaWillems commented
> Great description on how to use it.
> 
> For some unknown reason, this sample "runs" incredibly slow on my machine (multiple seconds per frame). But when the Vulkan Configurator is running as well, I don't get any output anymore and the speed is as expected. Any idea on that?

That seems to be a bug with the validation layers. I noticed this too, but couldn't reproduce :(

2024-03-07 19:21 UTC, SaschaWillems commented on samples/extensions/shader_debugprintf/README.adoc
> +The default buffer size for debug outputs is limited. If you output a lot of messages, e.g. by doing a printf per fragment shader invocation, this may not suffice and you'll get a validation warning
Note that I'm aware of. I didn't find anything in this regards in any of the SDK documents or the LunarG white papers.

2024-03-07 19:22 UTC, SaschaWillems commented on samples/extensions/shader_debugprintf/README.adoc
> +This **does not** apply to outputting messages in graphics debuggers.
Both. Graphics debuggers don't care for the buffer size and thus changing it with VkConfig has no effect.

2024-03-07 19:26 UTC, SaschaWillems commented on samples/extensions/shader_debugprintf/shader_debugprintf.cpp
> +	VkResult result = volkInitialize();
Thanks. The multiple layers of abstraction in the framework always makes it hard to find those things :/

2024-03-07 19:29 UTC, SaschaWillems commented on samples/extensions/shader_debugprintf/README.adoc
> +    validation_features.enabledValidationFeatureCount = 1;
I'll use `size()`. For people learning from our samples it imo makes it easier if they see that this can be a vector of enables.

2024-03-11 09:52 UTC, gary-sweet commented
This no longer crashes for me, but I'm still seeing:

```
[error] [framework/platform/platform.cpp:175] Error Message: Couldn't request feature from device as VK_KHR_get_physical_device_properties2 isn't enabled!
[error] [framework/platform/platform.cpp:176] Failed when running application shader_debugprintf
    71:05:42.547 nxserverlib: Vulkan Display(0x7e5c000ee0) unregistered

```

2024-03-11 10:00 UTC, SaschaWillems commented
Thank you very much for testing :)

I guess that error is caused by #938

Currently the framework will always enable all features of an extension at the time it's requested. I'll see if I can do a workaround for that.

2024-03-11 13:25 UTC, asuessenbach commented
I think, @gary-sweet's issue here is, that `VK_KHR_get_physical_device_properties2` is not enabled (is it supported, at all?), even though it has been added in `ShaderDebugPrintf::create_instance`! Should have failed there, then.

2024-03-11 14:02 UTC, gary-sweet commented
> I think, @gary-sweet's issue here is, that `VK_KHR_get_physical_device_properties2` is not enabled (is it supported, at all?), even though it has been added in `ShaderDebugPrintf::create_instance`! Should have failed there, then.

We do support VK_KHR_get_physical_device_properties2, so it's not obvious what the issue is. I'll do some degugging.

2024-03-11 14:31 UTC, gary-sweet commented
> I'll do some debugging.

It looks like this sample is creating its own VkInstance which it then constructs the Instance() object from. This appears to bypass a bunch of the extension enabling that happens in the Instance main constructor (all the enable_extension() stuff). The end result is that the Instance object doesn't think the extension is enabled, even though it actually is in the contained VkInstance.

2024-03-11 14:58 UTC, SaschaWillems commented
Yeah, it's similar to the profiles example. The framework assumes some stuff, even if you create your own instance, which in turn causes problems like these. Since the mentioned extension is not required by the sample I'm kinda hesitant to enable it. But that's probably the only way to fix that without adjusting the framework.

2024-03-11 17:14 UTC, SaschaWillems commented
This is kinda hard to debug, and I feel like this is platform-specific. The only place where this error is thrown is in (hpp_)phyiscal_device.h and at least on Windows I never even enter that code when running my sample. So we probably do something different/specific when running on your platform that causes the assert to trigger. I'll somehow try to reproduce this on Windows.

2024-03-15 09:04 UTC, SaschaWillems commented
Sorry, this currently fails after merging main. Lots of framework changes and at least something missing for me to continue working on this, see #985,

2024-03-15 13:48 UTC, gary-sweet requested changes
I believe this is now missing an entry in samples/CMakeLists.txt. This means the sample isn't currently runnable and doesn't appear in the samples lists in the help.

2024-03-15 14:10 UTC, SaschaWillems commented
Welp, probably happened while merging with main. Thanks for letting me know, will fix.

2024-03-15 14:24 UTC, SaschaWillems commented
Can you check again? Afair the list in that cmake file is purely optional. I'm actually not sure why that list of samples in there even exist. CMake should do a folder traversal and adds all samples it can find, no matter if the sample is explicitly added in that list or not.

2024-03-15 14:25 UTC, gary-sweet commented
> Can you check again? Afair the list in that cmake file is purely optional. I'm actually not sure why that list of samples in there even exist. CMake should do a folder traversal and adds all samples it can find, no matter if the sample is explicitly added in that list or not.

Well that's odd then, because the sample didn't exist for me unless I hacked it into that file.

2024-03-15 14:27 UTC, SaschaWillems commented
That's interesting. I just reran cmake and deleted the cache beforehand and the sample is somehow picked up. Will have to investigate.

2024-03-15 14:30 UTC, SaschaWillems commented
Added it to the CMake file anyway. Can't hurt ;)

2024-03-15 14:35 UTC, gary-sweet commented
> That's interesting. I just reran cmake and deleted the cache beforehand and the sample is somehow picked up. Will have to investigate.

Hmm. So I trashed my build folders completely and rebuilt and then it appeared, without the entry in cmake. It's possible that the cmake generate hadn't run, which is what I was seeing.

2024-03-15 15:14 UTC, gary-sweet approved these changes
The fact that shader-printf 'just works' (provided that you support VK_KHR_shader_non_semantic_info) had kind of passed me by and I had to scratch my head for a little bit when I saw it working with my driver to figure out why!

What a very useful thing, and an excellent sample.

[If I had an extra button to auto-rotate the model it would be even better (since I have no other way to rotate API samples), but I can always add one later on.]

2024-03-25 15:55 UTC, merged