Streamline swapchain classes
KhronosGroup/Vulkan-Samples pull request #973
Opened 2024-03-10 06:15 UTC by jherico

## Description

Fixes #972

Updates to `Swapchain` & `HPPSwapchain`

* Eliminate the `surface_formats` and `preset_modes` which are only ever used during the swapchain creation in the constructor
* Eliminate the `image_usage_flags` member in favor of the `SwapchainProperties`/`HPPSwapchainProperties` `image_usage` member
* Redefine all constructors in terms of a private constructor that accepts a ``SwapchainProperties`/`HPPSwapchainProperties` parameter
* Convert `SwapchainProperties::image_usage` from `VkImageUsageFlags` to `std::set<VkImageUsageFlagBits>`
  * I'd have preferred to leave it and use `VkImageUsageFlags` everywhere in the C bindings code, but then all the overloaded constructors and downstream members can't distinguish between `VkImageUsageFlags` and `uint32_t`.  This isn't a problem in the C++ bindings because `vk::ImageUsageFlags` isn't the same fundamental type as `uint32_t`.

Other files
* Updated `HPPApiVulkanSample` and `HPPRenderContext` swapchain utility functions to use `vk::ImageUsageFlags` instead of `std::set<vk::ImageUsageFlagBits>`
* Updated `HPPRenderContext` and `RenderContext` to remove the unused `swapchain_properties` member.

## General Checklist:

Please ensure the following points are checked:

- [X] My code follows the [coding style](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Code-Style)
- [X] I have reviewed file [licenses](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template)
- [X] I have commented any added functions (in line with Doxygen)
- [X] I have commented any code that could be hard to understand
- [ ] My changes do not add any new compiler warnings
- [ ] My changes do not add any new validation layer errors or warnings
- [X] I have used existing framework/helper functions where possible
- [ ] My changes do not add any regressions
- [ ] I have tested every sample to ensure everything runs correctly
- [ ] This PR describes the scope and expected impact of the changes I am making

 Note: The Samples CI runs a number of checks including:
 - [X] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
 - [ ] My changes build on Windows, Linux, macOS and Android. Otherwise I have [documented any exceptions](https://github.com/KhronosGroup/Vulkan-Samples/tree/main/CONTRIBUTING.adoc#General-Requirements)

2024-03-11 10:22 UTC, gary-sweet submitted a review, later dismissed

2024-03-11 20:51 UTC, JoseEmilio-ARM requested changes
As discussed in #963, please let that be merged before this one, thanks!

2024-03-18 13:52 UTC, asuessenbach commented on framework/core/hpp_swapchain.cpp
> +std::set<BitType> flags_in(const vk::Flags<BitType> &flags)
Maybe some more descriptive name than `flags_in`? Like `to_set`, or `split` or so?
And why do you sort the flags into a `std::set`, not a `std::vector`?

2024-03-18 13:52 UTC, asuessenbach commented on framework/core/hpp_swapchain.cpp
> +                           const HPPSwapchainProperties &inittial_properties) :
typo: `inittial_properties`

2024-07-03 14:01 UTC, marty-johnson59 commented
Hi @jherico, any thoughts on resolving the comments above?  How can we best move this one forward?  Thanks

2024-08-22 15:34 UTC, marty-johnson59 commented
Closing this PR as it looks like the issues addressed here have already been fixed.  Please re-open if there's more to do.  Thanks!

2024-08-22 15:34 UTC, closed without merging